/**********************
 *      INCLUDES
 *********************/
#include "port_cfg.h"

#include "std_header.h"
#include "mmk_app.h"
#include "mmi_common.h"
#include "mmk_timer.h"
#include "mmi_module.h"

#include "lebao.h"
#include "lebao_style.h"
#include "lebao_base.h"

#include "lebao_ctrl.h"
#include "lebao_misc.h"

#include "lebao_id.h"
#include "lebao_text.h"
#include "lebao_image.h"

/*********************
 *      DEFINES
 *********************/

/**********************
 *      TYPEDEFS
 **********************/

/**********************
 *  STATIC PROTOTYPES
 **********************/
static MMI_RESULT_E lebao_null_win_func(MMI_WIN_ID_T win_id, MMI_MESSAGE_ID_E msg_id, DPARAM param);
static MMI_RESULT_E lebao_hook_win_func(MMI_WIN_ID_T win_id, MMI_MESSAGE_ID_E msg_id, DPARAM param);

/**********************
 *  STATIC VARIABLES
 **********************/

 // splash page
WINDOW_TABLE(MMI_LEBAO_SPLASH_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_SPLASH),
	CREATE_ANIM_CTRL(MMI_LEBAO_CTRL_ID_IMG_LOGO, MMI_LEBAO_WIN_ID_SPLASH),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// menu page
WINDOW_TABLE(MMI_LEBAO_MENU_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_MAINMENU),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TITLE),
	CREATE_LISTBOX_CTRL(GUILIST_TEXTLIST_E,		MMI_LEBAO_CTRL_ID_LIST_MENU),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// setting page
WINDOW_TABLE(MMI_LEBAO_SETTING_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_SETTING),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TITLE),
	CREATE_LISTBOX_CTRL(GUILIST_TEXTLIST_E,		MMI_LEBAO_CTRL_ID_LIST_SETTING),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// about page
#define MMI_LEBAO_ABOUT_WIN_TAB NULL

// charts page
WINDOW_TABLE(MMI_LEBAO_CHARTS_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_CHARTS),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TITLE),
	CREATE_LISTBOX_CTRL(GUILIST_TEXTLIST_E,		MMI_LEBAO_CTRL_ID_LIST_CHARTS),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// sub charts page
WINDOW_TABLE(MMI_LEBAO_SUB_CHART_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_SUB_CHART),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TITLE),
	CREATE_LISTBOX_CTRL(GUILIST_TEXTLIST_E,		MMI_LEBAO_CTRL_ID_LIST_CHARTS),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// music list page
WINDOW_TABLE(MMI_LEBAO_MUSICLIST_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_MUSICLIST),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TITLE),
	CREATE_LISTBOX_CTRL(GUILIST_TEXTLIST_E, MMI_LEBAO_CTRL_ID_LIST_MUSICLIST),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// option menu page
#define MMI_LEBAO_OPTION_WIN_TAB NULL

// player page
WINDOW_TABLE(MMI_LEBAO_PLAYER_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_PLAYER),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_SONG_NAME),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_SINGER_NAME),
	CREATE_BUTTON_CTRL(IMAGE_LEBAO_BTN_PREVIOU,	MMI_LEBAO_CTRL_ID_BTN_PREV),
	CREATE_BUTTON_CTRL(IMAGE_LEBAO_BTN_PLAY,	MMI_LEBAO_CTRL_ID_BTN_PLAY),
//	CREATE_BUTTON_CTRL(IMAGE_LEBAO_BTN_PAUSE,	MMI_LEBAO_CTRL_ID_BTN_PAUSE),
	CREATE_BUTTON_CTRL(IMAGE_LEBAO_BTN_NEXT,	MMI_LEBAO_CTRL_ID_BTN_NEXT),
	CREATE_BUTTON_CTRL(IMAGE_LEBAO_BTN_RING,	MMI_LEBAO_CTRL_ID_BTN_RING),
	CREATE_BUTTON_CTRL(IMAGE_LEBAO_BTN_FAVORITE,	MMI_LEBAO_CTRL_ID_BTN_FAVORITE),
	CREATE_BUTTON_CTRL(IMAGE_LEBAO_BTN_VOLUME,	MMI_LEBAO_CTRL_ID_BTN_VOLUME),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// volume page
WINDOW_TABLE(MMI_LEBAO_VOLUME_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_VOLUME),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TITLE),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_VOLUME),
	CREATE_BUTTON_CTRL(IMAGE_LEBAO_BTN_VOL_ADD,	MMI_LEBAO_CTRL_ID_BTN_VOL_ADD),
	CREATE_BUTTON_CTRL(IMAGE_LEBAO_BTN_VOL_SUB,	MMI_LEBAO_CTRL_ID_BTN_VOL_SUB),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// My favorites page
WINDOW_TABLE(MMI_LEBAO_LOCAL_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_LOCAL),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TITLE),
	CREATE_LISTBOX_CTRL(GUILIST_TEXTLIST_E,		MMI_LEBAO_CTRL_ID_LIST_LOCAL),
	CREATE_BUTTON_CTRL(IMAGE_LEBAO_BTN_DELETE,	MMI_LEBAO_CTRL_ID_BTN_DEL),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// search page
WINDOW_TABLE(MMI_LEBAO_SEARCH_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_SEARCH),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TITLE),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TIMER),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TIPS),
	CREATE_BUTTON_CTRL(IMAGE_LEBAO_RECORD_GRAY,	MMI_LEBAO_CTRL_ID_BTN_RECORD),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// waiting page
WINDOW_TABLE(MMI_LEBAO_WAITING_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_WAITING),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE, MMI_LEBAO_CTRL_ID_LABEL_TITLE),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE, MMI_LEBAO_CTRL_ID_LABEL_TIPS),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE, MMI_LEBAO_CTRL_ID_LABEL_TIMER),
	CREATE_ANIM_CTRL(MMI_LEBAO_CTRL_ID_IMG_LOADING, MMI_LEBAO_WIN_ID_WAITING),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	WIN_HIDE_STATUS,
	END_WIN
};

// order page
WINDOW_TABLE(MMI_LEBAO_ORDER_WIN_TAB) =
{
	WIN_FUNC((uint32)lebao_null_win_func),
	WIN_ID(MMI_LEBAO_WIN_ID_ORDER),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_TITLE),
	CREATE_ANIM_CTRL(MMI_LEBAO_CTRL_ID_IMG_QRCODE, 0),
	CREATE_LABEL_CTRL(GUILABEL_ALIGN_MIDDLE,	MMI_LEBAO_CTRL_ID_LABEL_SCAN),
	WIN_STYLE(WS_NO_DEFAULT_STYLE),
	WIN_HIDE_STATUS,
	WIN_MOVE_STYLE(MOVE_FORBIDDEN),
	END_WIN
};
#define MMI_LEBAO_ORDER_OPT_TAB NULL
#define MMI_LEBAO_VIP_WIN_TAB NULL

// confirm page
#define MMI_LEBAO_CONFIRM_WIN_TAB NULL

// login page
#define MMI_LEBAO_LOGIN_WIN_TAB NULL

#define MMI_LEBAO_CONTACT_WIN_TAB NULL

#define MMI_LEBAO_SONGLIST_WIN_TAB NULL

static struct
{
	int pageId;
	uint32* tab;
	int winId;
} _resWinId[] = {
	{ LEBAO_PAGE_SRV,		NULL, 0 },
	{ LEBAO_PAGE_CTRL,		NULL, 0 },
	{ LEBAO_PAGE_SPLASH,	MMI_LEBAO_SPLASH_WIN_TAB,	MMI_LEBAO_WIN_ID_SPLASH },
	{ LEBAO_PAGE_MENU,		MMI_LEBAO_MENU_WIN_TAB,		MMI_LEBAO_WIN_ID_MAINMENU },
	{ LEBAO_PAGE_CHART,		MMI_LEBAO_CHARTS_WIN_TAB,	MMI_LEBAO_WIN_ID_CHARTS },
	{ LEBAO_PAGE_MUSICLIST,	MMI_LEBAO_MUSICLIST_WIN_TAB, MMI_LEBAO_WIN_ID_MUSICLIST },
	{ LEBAO_PAGE_PLAYER,	MMI_LEBAO_PLAYER_WIN_TAB,	MMI_LEBAO_WIN_ID_PLAYER },
	{ LEBAO_PAGE_VOLUME,	MMI_LEBAO_VOLUME_WIN_TAB,	MMI_LEBAO_WIN_ID_VOLUME },
	{ LEBAO_PAGE_LOCAL,		MMI_LEBAO_LOCAL_WIN_TAB,	MMI_LEBAO_WIN_ID_LOCAL },
	{ LEBAO_PAGE_SEARCH,	MMI_LEBAO_SEARCH_WIN_TAB,	MMI_LEBAO_WIN_ID_SEARCH },
	{ LEBAO_PAGE_RECORD,	NULL, 0 },
	{ LEBAO_PAGE_WAITING,	MMI_LEBAO_WAITING_WIN_TAB,	MMI_LEBAO_WIN_ID_WAITING },
	{ LEBAO_PAGE_ORDER,		MMI_LEBAO_ORDER_WIN_TAB,	MMI_LEBAO_WIN_ID_ORDER },
	{ LEBAO_PAGE_SETTING,	MMI_LEBAO_SETTING_WIN_TAB,  MMI_LEBAO_WIN_ID_SETTING },
	{ LEBAO_PAGE_STREAM,	NULL, 0 },
	{ LEBAO_PAGE_ABOUT,		NULL, 0 },
	{ LEBAO_PAGE_CONFIRM,	NULL, 0 },
	{ LEBAO_PAGE_OPTION,	NULL, 0 },
	{ LEBAO_PAGE_VIP,		NULL, 0 },
	{ LEBAO_PAGE_LOGIN,		NULL, 0 },
	{ LEBAO_PAGE_CONTACT,	NULL, 0 },
	{ LEBAO_PAGE_SUB_CHART,	MMI_LEBAO_SUB_CHART_WIN_TAB,	MMI_LEBAO_WIN_ID_SUB_CHART },
	{ LEBAO_PAGE_SONGLIST,	NULL, 0 },
};

/**********************
 *      MACROS
 **********************/

/**********************
 *   GLOBAL FUNCTIONS
 **********************/
MMI_HANDLE_T lebao_create_win(const int pageId) 
{
	MMI_HANDLE_T handle = NULL;

	if (pageId <= 0 || pageId > LEBAO_PAGE_SONGLIST)
		return NULL;

	if (_resWinId[pageId].tab == NULL || _resWinId[pageId].winId == 0)
		return NULL;

	if (MMK_IsOpenWin(_resWinId[pageId].winId))
		return NULL;

	handle = MMK_CreateWin((uint32*)_resWinId[pageId].tab, PNULL);
	if (handle != NULL)
		MMK_SetWinHookFunc(handle, lebao_hook_win_func);

	helper_debug_printf("pageId=%d, handle=0x%x", pageId, handle);
	return handle;
}

void lebao_close_win(const int pageId)
{
	helper_debug_printf("pageId=%d", pageId);

	if (pageId <= 0 || pageId > LEBAO_PAGE_SONGLIST)
		return;

	if (_resWinId[pageId].tab == NULL || _resWinId[pageId].winId < MMI_LEBAO_WIN_ID_SPLASH)
		return;
	
	if (MMK_IsOpenWin(_resWinId[pageId].winId)) {
		MMK_CloseWin(_resWinId[pageId].winId);
	}
}

BOOLEAN	lebao_is_win_opened(const int pageId)
{
	if (pageId <= 0 || pageId > LEBAO_PAGE_SONGLIST)
		return FALSE;

	if (_resWinId[pageId].tab == NULL || _resWinId[pageId].winId == 0)
		return FALSE;

	if (MMK_IsOpenWin(_resWinId[pageId].winId))
		return TRUE;

	return FALSE;
}

int lebao_get_pageid(int win_id)
{
	int  i = 0, count = 0;
	if(win_id < MMI_LEBAO_WIN_ID_SPLASH || win_id > MMI_LEBAO_WIN_ID_SONGLIST)
		return 0;

	for(i = LEBAO_PAGE_SPLASH; i <= LEBAO_PAGE_SONGLIST; i++) {
		if(_resWinId[i].winId == win_id)
			return _resWinId[i].pageId;
	}

	return 0;
}

void lebao_close_win_handle(MMI_HANDLE_T handle)
{
	if (MMK_IsOpenWin(handle))
		MMK_CloseWin(handle);
}

/**********************
 *   STATIC FUNCTIONS
 **********************/
static MMI_RESULT_E lebao_null_win_func(MMI_WIN_ID_T win_id, MMI_MESSAGE_ID_E msg_id, DPARAM param)
{
	(void)win_id;
	(void)msg_id;
	(void)param;

	return MMI_RESULT_FALSE;
}

static MMI_RESULT_E lebao_back_btn_click(void) 
{
	MMK_DispMsgToFocusWin(MSG_CTL_CANCEL, NULL);
	return MMI_RESULT_TRUE;
}

static MMI_RESULT_E lebao_hook_win_func(MMI_WIN_ID_T win_id, MMI_MESSAGE_ID_E msg_id, DPARAM param)
{
	// displays the back button of the wide screen
	if(msg_id == MSG_OPEN_WINDOW) {
		if(win_id != MMI_LEBAO_WIN_ID_SPLASH && win_id != MMI_LEBAO_WIN_ID_MAINMENU) {
			// 320x170, 480x200
			if(LEBAO_SCREEN_WIDTH > 240 && LEBAO_SCREEN_WIDTH > LEBAO_SCREEN_HEIGHT) {
				GUI_RECT_T backRect = { 5, 0, 5 + 36, 0 + 36 }; // 36 x 36
				MMI_CTRL_ID_T backId = MMI_LEBAO_CTRL_ID_BTN_BACK;
				GUIBUTTON_INIT_DATA_T initData = {0};
				
				initData.both_rect.h_rect = initData.both_rect.v_rect = backRect;
				initData.bg.bg_type = GUI_BG_IMG;
				initData.bg.img_id = IMAGE_LEBAO_BTN_BACK;
				
				if(GUIBUTTON_CreateDynamic(win_id, backId, &initData) != NULL) {
					GUIBUTTON_SetRect(backId, &backRect);
					GUIBUTTON_SetRunSheen(backId, FALSE);
					GUIBUTTON_SetCallBackFunc(backId, &lebao_back_btn_click);
				}
			}
		}
	}

	// hide softkeybar
	if(msg_id == MSG_OPEN_WINDOW || msg_id == MSG_FULL_PAINT) {
		#if defined(LEBAO_HIDE_SOFTKEYBAR)
			GUIWIN_SetSoftkeyVisible(win_id, FALSE);
		#endif
	}

	// quit app
	if(msg_id == MSG_APP_RED) {
		#if 1
			MMIAPIMENU_QuitLebao();
			return MMI_RESULT_TRUE; // Must be true !!! otherwise, crash
		#else
			MMK_PostMsg(win_id, MSG_CTL_CANCEL, PNULL, 0);
			return MMI_RESULT_TRUE;
			// or
			// MMK_CloseWin(win_id);
			// or	
			// int pageId = lebao_get_pageid(win_id);
			// if(pageId != 0 && pageId != LEBAO_PAGE_SPLASH)
			//	 lebao_event_send(EVT_CTRL_LEBAO_CLOSE_PAGE, LEBAO_PAGE_CTRL, pageId, 0);
		#endif
	}
	
	return MMI_RESULT_FALSE;
}

