/****************************************************************************
** File Name:      mmiphs_app.h                                                *
** Author:                                                                 *
** Date:           03/22/2006                                              *
** Copyright:      2006 TLT, Incoporated. All Rights Reserved.       *
** Description:    This file is used to describe the PHS                   *
/****************************************************************************
**                         Important Edit History                          *
** ------------------------------------------------------------------------*
** DATE           NAME             DESCRIPTION                             *
** 03/2006       Jianshengqi         Create
** 
****************************************************************************/
#ifndef  _MMI_ZDT_APP_H_    
#define  _MMI_ZDT_APP_H_   

#ifdef __cplusplus
    extern "C"
    {
#endif
/**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/

#include "zdt_common.h"
#include "zdt_db.h"
#include "zdt_id.h"
#include "zdt_menutable.h"
#include "zdt_nv.h"
#include "zdt_text.h"
#include "zdt_image.h"
#include "zdt_anim.h"
#ifdef ZDT_LED_SUPPORT
#include "zdt_led.h"
#endif

#ifdef ZDT_SMS_SUPPORT
#include "zdt_sms.h"
#endif
#if defined(ZDT_GPS_SUPPORT)||defined(ZDT_W217_FACTORY_GPS)
#include "zdt_gps.h"
#endif
#ifdef ZDT_GSENSOR_SUPPORT
#include "zdt_gsensor.h"
#endif
#ifdef ZDT_HSENSOR_SUPPORT
#include "zdt_hsensor.h"
#endif
#ifdef ZDT_NET_SUPPORT
#include "zdt_net.h"
#ifdef ZDT_PLAT_HYHL_SUPPORT
#include "zdt_hyhl.h"
#endif
#ifdef ZDT_PLAT_YX_SUPPORT
#include "zdt_yx.h"
#endif
#endif
#ifdef ZDT_PLAT_SHB_SUPPORT
#include "zdt_shb.h"
#endif
#ifdef ZDT_WIFI_SUPPORT
#include "wifisupp_api.h"
#endif

#define YX_DB_APP_DOMAIN_URL "4g.watch.ecellsz.com"

#define ZDTAPP_TRACE            ZDT_Trace

typedef struct
{
       uint8 *        str;
	uint32         len; 
} MMI_ZDT_DATA_T;

typedef struct
{
	SIGNAL_VARS
       MMI_ZDT_DATA_T data;
} MMI_ZDT_SIG_T ;

extern BOOLEAN is_zdt_jt_mode;

extern void MMIZDT_AppInit(void);
extern void MMIZDT_RegWinIdNameArr(void);
extern void MMIZDT_InitModule(void);
extern void MMIZDT_RegMenuGroup(void);
extern void MMIZDT_RegNv(void);
extern BOOLEAN MMIZDT_MoCallByNum(MN_DUAL_SYS_E dual_sys,uint8 * num_str);

extern BOOLEAN  MMIZDT_SendSigTo_APP(ZDT_APP_SIG_E sig_id, uint8 * data_ptr, uint32 data_len);
extern void MMIZDT_ResetFactory(void);

#ifdef ZDT_WIFI_SUPPORT
typedef int (*MMIZDTWIFIHANDLER) (uint8 loc_ok,void * pWifiData);
typedef struct _MMIZDTWIFI_LINK_DATA_t
{
    uint32 timeout;
    MMIZDTWIFIHANDLER rcv_handle;
} MMIZDTWIFI_LINK_DATA_T;

typedef struct _MMIZDTWIFI_LINK_NODE_t
{
       MMIZDTWIFI_LINK_DATA_T  data;
       struct _MMIZDTWIFI_LINK_NODE_t * next_ptr;
} MMIZDTWIFI_LINK_NODE_T;

extern BOOLEAN MMIZDTWIFI_PowerOn_LocOnce(void);
extern BOOLEAN MMIZDTWIFI_PowerOff_LocOnce(void);
extern BOOLEAN MMIZDTWIFI_IsLocOnceStart(void);
extern void MMIZDT_WIFI_OnOff(uint8 val) ;
extern uint8 MMIZDT_WIFI_GetOpen(void);
extern void MMIZDT_WIFI_SetOpen(uint8 val);
extern BOOLEAN MMIZDTWIFI_API_LocStart(uint32 time_s,MMIZDTWIFIHANDLER loc_callback);
extern BOOLEAN MMIZDTWIFI_API_LocStop(void);

#endif

#if defined(ZDT_W217_FACTORY_WIFI)// WUXX_20231212 wifi
uint8 MMIZDTWIFI_Start(void);
void MMIZDTWIFI_Stop(void);

void ZDT_W217_WIFI_ON_OFF_for_Net(BOOLEAN isOn);

#endif

#if defined(ZDT_GPS_SUPPORT)||defined(ZDT_W217_FACTORY_GPS)
typedef int (*MMIZDTGPSHANDLER) (uint8 loc_ok,void * pGpsData);
typedef struct _MMIZDTGPS_LINK_DATA_t
{
    uint32 timeout;
    MMIZDTGPSHANDLER rcv_handle;
} MMIZDTGPS_LINK_DATA_T;

typedef struct _MMIZDTGPS_LINK_NODE_t
{
       MMIZDTGPS_LINK_DATA_T  data;
       struct _MMIZDTGPS_LINK_NODE_t * next_ptr;
} MMIZDTGPS_LINK_NODE_T;

extern void MMIZDTGPS_PowerOn_Interval(uint16 time_min);
extern void MMIZDTGPS_PowerOff_Interval(void);
extern BOOLEAN MMIZDTGPS_IsNeedLoc(void);
extern  void MMIZDTGPS_PowerOn(void);
extern  void MMIZDTGPS_PowerOff(void);
extern BOOLEAN MMIZDTGPS_API_LocStart(uint32 time_s,MMIZDTGPSHANDLER loc_callback);
extern BOOLEAN MMIZDTGPS_API_LocEnd(void);

extern BOOLEAN MMIZDTGPS_PowerOff_LocOnce(void);

#endif

#if defined(ZDT_W217_FACTORY_GPS)// wuxx add 20231127

extern void MMIZDTGPS_PowerOn_for_w217(void);
extern void MMIZDTGPS_PowerOff_for_w217(void);

// wuxx_20231219  gps
extern void MMIZDTGPS_ClearGpsData(void);

#endif


PUBLIC BOOLEAN ZDT_Reject_Call(uint8 *number);
PUBLIC BOOLEAN ZDT_Device_Disable( GUI_POINT_T tp_point);
PUBLIC MMI_IMAGE_ID_T ZDT_PB_GetDispInfoContent(uint8 *tele_num, uint8 tele_len, wchar *in_str, BOOLEAN is_mo_call);
PUBLIC uint8 MMIZDT_GetFirstPWON(void);
PUBLIC BOOLEAN MMIZDT_NV_SetFirstPWON(uint8 first_pwon);
#ifdef SETUP_WIZARD_SUPPORT
PUBLIC uint8 MMIZDT_Get_Setup_Wizard_Status(void);
PUBLIC void MMIZDT_NV_Set_Setup_Wizard(uint8 status);
#endif

#ifdef ZDT_VIDEOCHAT_SUPPORT
PUBLIC void Video_Call_RequestContactSuccess(VIDEO_USER_INFO *video_call_user_info);
PUBLIC uint8 Video_Call_Incoming(VIDEO_CALL_INFO video_call_info);
PUBLIC uint8 Video_Call_Incoming_Test();
PUBLIC void Video_Call_Remote_Hangup();
#endif

//************dropdown win************************
#define DROPDOWN_TOOLS_MARGIN_BOTTOM DP2PX_VALUE(10)
#define DROPDOWN_TOOLS_IMG_HEIGHT DP2PX_VALUE(60)
#define DROPDOWN_TOOLS_IMG_WIDTH DP2PX_VALUE(60)
#define DROPDOWN_TOOLS_TOP MMI_MAINSCREEN_HEIGHT-DROPDOWN_TOOLS_MARGIN_BOTTOM-DROPDOWN_TOOLS_IMG_HEIGHT
#define DROPDOWN_TOOLS_RECT {DP2PX_VALUE(10),DROPDOWN_TOOLS_TOP,DP2PX_VALUE(60),MMI_MAINSCREEN_HEIGHT-DROPDOWN_TOOLS_MARGIN_BOTTOM}
#define DROPDOWN_SOUND_RECT {DP2PX_VALUE(70),DROPDOWN_TOOLS_TOP,DP2PX_VALUE(120),MMI_MAINSCREEN_HEIGHT-DROPDOWN_TOOLS_MARGIN_BOTTOM}
#define DROPDOWN_SETTINGS_RECT {DP2PX_VALUE(130),DROPDOWN_TOOLS_TOP,DP2PX_VALUE(180),MMI_MAINSCREEN_HEIGHT-DROPDOWN_TOOLS_MARGIN_BOTTOM}
#define DROPDOWN_TORCH_RECT {DP2PX_VALUE(190),DROPDOWN_TOOLS_TOP,DP2PX_VALUE(240),MMI_MAINSCREEN_HEIGHT-DROPDOWN_TOOLS_MARGIN_BOTTOM}
#define MMIDROPDOWNWIN_HEIGHT MMI_MAINSCREEN_HEIGHT
#define MMIDROPDOWNWIN_WIDTH MMI_MAINSCREEN_WIDTH
#define MMIDROPDOWNWIN_RECT {0,0,MMIDROPDOWNWIN_WIDTH - 1,MMIDROPDOWNWIN_HEIGHT - 1}
#define MMIDROPDOWNWIN_BGCOLOR MMI_BLACK_COLOR
#define MMIDROPDOWNWIN_ROIREGION {0,DP2PX_VALUE(210),MMIDROPDOWNWIN_WIDTH,MMIDROPDOWNWIN_HEIGHT}
#define MMIDROPDOWNWIN_INIT_POS (-MMIDROPDOWNWIN_HEIGHT)
#define MMIDROPDOWNWIN_STOP_POS 0
#define MMIDROPDOWNWIN_END_POS (-MMIDROPDOWNWIN_HEIGHT)
#define DROPDOWN_TOP_TOOLS_IMG_MARGIN_TOP DP2PX_VALUE_Y(52)
#define DROPDOWN_TOP_TOOLS_IMG_MARGIN_LEFT DP2PX_VALUE(21)
#define DROPDOWN_TOP_TOOLS_BG_MARGIN_TOP DP2PX_VALUE_Y(43)
#define DROPDOWN_TOP_TOOLS_BG_MARGIN_LEFT DP2PX_VALUE(12)
#define DROPDOWN_TOP_TOOLS_IMG_HEIGHT DP2PX_VALUE(48)
#define DROPDOWN_TOP_TOOLS_IMG_WIDTH DP2PX_VALUE(48)
#define DROPDOWN_TOP_TOOLS_BG_HEIGHT DP2PX_VALUE_Y(66)
#define DROPDOWN_TOP_TOOLS_BG_WIDTH DP2PX_VALUE(66)
#define DROPDOWN_TOP_TOOLS_OFFSET DP2PX_VALUE(27)
#define DROPDOWN_TOP_TOOLS_BG_OFFSET DP2PX_VALUE(9)
//#define DROPDOWN_TOP_TOOLS_LIGHT_RECT {10,DROPDOWN_TOP_TOOLS_MARGIN_TOP,70,DROPDOWN_TOP_TOOLS_MARGIN_TOP+DROPDOWN_TOP_TOOLS_IMG_HEIGHT}
//#define DROPDOWN_SOUND_RECT {90,DROPDOWN_TOOLS_TOP,150,MMI_MAINSCREEN_HEIGHT-DROPDOWN_TOOLS_MARGIN_BOTTOM}
#define DROPDOWN_WEATHER_RECT DP2PX_RECT(15,28,225,144)
#define DROPDOWN_LOGIN_ICON_POINT DP2PX_POINT(78,10)
#define DROPDOWN_WEATHER_LOCATION_POINT DP2PX_POINT(120,40)
#define DROPDOWN_WEATHER_ICON_POINT DP2PX_POINT(30,40)
#define DROPDOWN_WEATHER_CITY_RECT {DP2PX_VALUE(150),DP2PX_VALUE(40),(MMI_MAINSCREEN_WIDTH -DP2PX_VALUE(20)),DP2PX_VALUE(70)}
#define DROPDOWN_DATA_IN_OUT_ICON_POINT DP2PX_POINT(55,2)
#define DROPDOWN_WEATHER_TEMP_RECT {DP2PX_VALUE(140),DP2PX_VALUE(110),(MMI_MAINSCREEN_WIDTH -1),DP2PX_VALUE(160)}  
#define DROPDOWN_WEATHER_TEXT_RECT DP2PX_RECT(150,70,240,100)
#define DROPDOWN_WEATHER_ICON_WIDTH DP2PX_VALUE(82)
#define DROPDOWN_WEATHER_ICON_HEIGHT DP2PX_VALUE(82)
//************************************************


//*****************setup wizard*******************************
#if defined(MAINLCD_DEV_SIZE_240X284)
#define SETUP_WIZARD_NEXT_RECT {20,214,220,254};
#else
#define	SETUP_WIZARD_NEXT_RECT DP2PX_RECT(20,184,220,224);
#endif
#define SETUP_WIZARD_NEXT_BG_COLOR 0x1185FC
#define SETUP_WIZARD_QRCODE_RECT DP2PX_RECT(40, 20, 168, 158)
#if defined(MAINLCD_DEV_SIZE_240X284)
#define SETUP_WIZARD_TITLE_RECT {0,0,MMI_MAINSCREEN_WIDTH,45}
#else
#define SETUP_WIZARD_TITLE_RECT {0,4,128,24}
#endif
#define SETUP_WIZARD_NEXT_TIPS_RECT DP2PX_RECT(35,150,205,180)
#define SETUP_WIZARD_HAS_BIND_RECT DP2PX_RECT(50,90,190,120)
#define SETUP_WIZARD_NEXT_BIND_PAY_RECT DP2PX_RECT(37,120,103,150)
#define SETUP_WIZARD_TO_BIND_PAY_RECT DP2PX_RECT(137,120,203,150)
#define SETUP_WIZARD_BIND_PAY_TIPS_RECT DP2PX_RECT(0,40,240,80)
//************************************************

//****************VIDEO CALL*******************************
#define VIDEO_CALL_CONTACT_LIST_X 0
#define VIDEO_CALL_CONTACT_LIST_Y DP2PX_VALUE(30)
#define VIDEO_CALL_INCOMING_HANGUP_RECT {DP2PX_VALUE(34),DP2PX_VALUE(155),DP2PX_VALUE(86),DP2PX_VALUE(207)}
#define VIDEO_CALL_INCOMING_ACCRPT_RECT {DP2PX_VALUE(154),DP2PX_VALUE(155),DP2PX_VALUE(206),DP2PX_VALUE(207)}
#define VIDEO_CALL_OUT_HANGUP_RECT {DP2PX_VALUE(94),DP2PX_VALUE(155),DP2PX_VALUE(156),DP2PX_VALUE(235)}
#define VIDEO_CALL_IN_VIDEO_HANGUP_RECT {DP2PX_VALUE(94),DP2PX_VALUE(155),DP2PX_VALUE(156),DP2PX_VALUE(235)}
#define VIDEO_CALL_STATE_RECT {0,DP2PX_VALUE(5),MMI_MAINSCREEN_WIDTH,DP2PX_VALUE(35)}
#define VIDEO_CALL_NAME_RECT {0,DP2PX_VALUE(40),MMI_MAINSCREEN_WIDTH,DP2PX_VALUE(70)}
#define VIDEO_CALL_HEAD_IMG_Y DP2PX_VALUE(40)
//***********************************************

//***************find friend************************
#define SEARCH_ING_STR_RECT DP2PX_RECT(0,10,240,40)
#define SEARCH_ING_TIP_STR_RECT DP2PX_RECT(60,177,180,235)
#define FIND_FRIEND_PING_X DP2PX_VALUE(25)
#define FIND_FRIEND_PING_Y DP2PX_VALUE_Y(73)
#define FIND_FRIEND_PONG_X DP2PX_VALUE(100)
#define FIND_FRIEND_PONG_Y DP2PX_VALUE_Y(112)
#define FIND_FRIEND_WAITING_X DP2PX_VALUE(145)
#define FIND_FRIEND_WAITING_Y DP2PX_VALUE_Y(73)
#define FIND_FRIEND_TIME_OUT 30000
//****************************************

//****************all app list*******************************
#define APP_LIST_RECT {0,0,MMI_MAINSCREEN_WIDTH,MMI_MAINSCREEN_HEIGHT}
#ifdef APP_COLUMNS_3
#define APP_LIST_ITEM_MARGIN_SPACE {7,3,8,10} //icon_item_hspace;icon_item_vspace;iconlist_hmargin;iconlist_vmargin;
#define APP_LIST_ITEM_ICON_WIDTH 70
#define APP_LIST_ITEM_ICON_HEIGHT 65
#else
#define APP_LIST_ITEM_MARGIN_SPACE {5,5,8,10} //icon_item_hspace;icon_item_vspace;iconlist_hmargin;iconlist_vmargin;
#define APP_LIST_ITEM_ICON_WIDTH 45
#define APP_LIST_ITEM_ICON_HEIGHT 45
#endif
//***********************************************

//************dropup win************************
#define MMIDROPUPWIN_HEIGHT MMI_MAINSCREEN_HEIGHT+3 //解决滑动到顶后有几个像素的高度没刷新
#define MMIDROPUPWIN_WIDTH MMI_MAINSCREEN_WIDTH
#define MMIDROPUPWIN_RECT {0,0,MMIDROPUPWIN_WIDTH,MMIDROPUPWIN_HEIGHT}
#define MMIDROPUPWIN_BGCOLOR MMI_BLACK_COLOR
#define MMIDROPUPWIN_ROIREGION {0,0,MMIDROPUPWIN_WIDTH,30}
#define MMIDROPUPWIN_INIT_POS (MMIDROPUPWIN_HEIGHT)
#define MMIDROPUPWIN_STOP_POS 0
#define MMIDROPUPWIN_END_POS (MMIDROPUPWIN_HEIGHT)
//************************************************

//****************phone book and dialer*******************************
#define LAUNCHER_PHONEBOOK_LABEL_RECT {12,20,228,68}
#define LAUNCHER_DIALER_LABEL_RECT {12,76,228,124}
#define LAUNCHER_PHONEBOOK_AND_DIALER_LABEL_TEXT_SPACE 15
//***********************************************

//****************wechat contact list *******************************
#define LAUNCHER_WECHAT_CONTACT_LIST_RECT {0,20,MMI_MAINSCREEN_WIDTH,MMI_MAINSCREEN_HEIGHT}
//***********************************************

//****************watch face 表盘 *******************************
#ifdef MAINLCD_DEV_SIZE_240X284
#define WATCH_PANEL_PREVIEW_IMG_HEGHT 190  //表盘预览
#define WATCH_PANEL_PREVIEW_IMG_WIDTH 160
#else
#define WATCH_PANEL_PREVIEW_IMG_HEGHT DP2PX_VALUE(180)  //表盘预览
#define WATCH_PANEL_PREVIEW_IMG_WIDTH DP2PX_VALUE(180)
#endif
#define WATCH_PANEL_PREVIEW_LEFT (MMI_MAINSCREEN_WIDTH-WATCH_PANEL_PREVIEW_IMG_WIDTH)/2
#define WATCH_PANEL_PREVIEW_TOP (MMI_MAINSCREEN_HEIGHT-WATCH_PANEL_PREVIEW_IMG_HEGHT)/2
#define WATCH_PANEL_PREVIEW_RIGHT MMI_MAINSCREEN_WIDTH-WATCH_PANEL_PREVIEW_LEFT
#define WATCH_PANEL_PREVIEW_BOTTOM MMI_MAINSCREEN_HEIGHT-WATCH_PANEL_PREVIEW_TOP
#define WATCH_PANEL_PREVIEW_IMG_RECT {WATCH_PANEL_PREVIEW_LEFT,WATCH_PANEL_PREVIEW_TOP,WATCH_PANEL_PREVIEW_RIGHT,WATCH_PANEL_PREVIEW_BOTTOM}

//太空人表盘
#define WATCH_PANEL_ASTRONAUT_DATE_MARGIN_BOTTOM DP2PX_VALUE_Y(27) //日期屏幕底部边距
#define WATCH_PANEL_ASTRONAUT_DATE_MARGIN_LEFT DP2PX_VALUE(146)  //日期屏幕左边距
#define WATCH_PANEL_ASTRONAUT_DATE_IMG_WIDTH DP2PX_VALUE(14)    //日期图片宽度
#define WATCH_PANEL_ASTRONAUT_DATE_Y MMI_MAINSCREEN_HEIGHT - WATCH_PANEL_ASTRONAUT_DATE_MARGIN_BOTTOM
#define WATCH_PANEL_ASTRONAUT_DATE_START_X WATCH_PANEL_ASTRONAUT_DATE_MARGIN_LEFT
#define WATCH_PANEL_ASTRONAUT_YEAR_START_X DP2PX_VALUE(33)
#define WATCH_PANEL_ASTRONAUT_TIME_IMG_WIDTH DP2PX_VALUE(26)    //时间图片宽度
#define WATCH_PANEL_ASTRONAUT_BATTERY_PERCENT_IMG_WIDTH DP2PX_VALUE(14)
#define WATCH_PANEL_ASTRONAUT_COLON_IMG_WIDTH DP2PX_VALUE(6)
#ifdef MAINLCD_DEV_SIZE_240X284
#define WATCH_PANEL_ASTRONAUT_TIME_MARGIN_TOP 59
#define WATCH_PANEL_ASTRONAUT_TIME_START_X 34
#define WATCH_PANEL_ASTRONAUT_BATTERY_PERCENT_MARGIN_RIGHT 50
#define WATCH_PANEL_ASTRONAUT_BATTERY_MARGIN_TOP 10
#define WATCH_PANEL_ASTRONAUT_POWER_START_X 126
#define WATCH_PANEL_ASTRONAUT_WEATHER_MARGIN_LEFT 25
#define WATCH_PANEL_ASTRONAUT_WEATHER_ICON_MARGIN_TOP 7
#define WATCH_PANEL_ASTRONAUT_WEATHER_MARGIN_TOP 10
#define WATCH_PANEL_ASTRONAUT_WEATHER_TEMPERATURE_ICON_START_X 93
#define WATCH_PANEL_ASTRONAUT_WEATHER_TEMPERATURE_IMG_WIDTH 14    //温度图片宽度
#define WATCH_PANEL_ASTRONAUT_TIME_SECOND_MARGIN_TOP 70
#define WATCH_PANEL_ASTRONAUT_TIME_SECOND_START_X 173
#define WATCH_PANEL_ASTRONAUT_TIME_SECOND_IMG_WIDTH 17
#define WATCH_PANEL_ASTRONAUT_TIME_X_OFFSET 3
#define WATCH_PANEL_ASTRONAUT_WEEK_MARGIN_BOTTOM 68
#else
#define WATCH_PANEL_ASTRONAUT_TIME_MARGIN_TOP DP2PX_VALUE_Y(42)
#define WATCH_PANEL_ASTRONAUT_TIME_START_X DP2PX_VALUE(65) 
#define WATCH_PANEL_ASTRONAUT_BATTERY_MARGIN_TOP DP2PX_VALUE_Y(6)
#define WATCH_PANEL_ASTRONAUT_POWER_START_X DP2PX_VALUE(115)
#define WATCH_PANEL_ASTRONAUT_BATTERY_PERCENT_MARGIN_RIGHT DP2PX_VALUE(38)
#define WATCH_PANEL_ASTRONAUT_WEATHER_MARGIN_LEFT DP2PX_VALUE(2)
#define WATCH_PANEL_ASTRONAUT_WEATHER_ICON_MARGIN_TOP DP2PX_VALUE_Y(4)
#define WATCH_PANEL_ASTRONAUT_WEATHER_MARGIN_TOP DP2PX_VALUE_Y(6)
#define WATCH_PANEL_ASTRONAUT_WEATHER_TEMPERATURE_ICON_START_X DP2PX_VALUE(74)
#define WATCH_PANEL_ASTRONAUT_WEATHER_TEMPERATURE_IMG_WIDTH DP2PX_VALUE(14)    //温度图片宽度
#define WATCH_PANEL_ASTRONAUT_TIME_SECOND_MARGIN_TOP DP2PX_VALUE_Y(70)
#define WATCH_PANEL_ASTRONAUT_TIME_SECOND_START_X DP2PX_VALUE(173)
#define WATCH_PANEL_ASTRONAUT_TIME_SECOND_IMG_WIDTH DP2PX_VALUE(17)
#define WATCH_PANEL_ASTRONAUT_TIME_X_OFFSET 0
#define WATCH_PANEL_ASTRONAUT_WEEK_MARGIN_BOTTOM DP2PX_VALUE_Y(58)
#endif
#define WATCH_PANEL_ASTRONAUT_WEEK_Y MMI_MAINSCREEN_HEIGHT-WATCH_PANEL_ASTRONAUT_WEEK_MARGIN_BOTTOM
#define WATCH_PANEL_ASTRONAUT_WEEK_X DP2PX_VALUE(163)

//海豚表盘
#define WATCH_PANEL_DOLPHIN_WEEK_MARGIN_BOTTOM DP2PX_VALUE_Y(30)
#define WATCH_PANEL_DOLPHIN_WEEK_MARGIN_LEFT DP2PX_VALUE(90)
#define WATCH_PANEL_DOLPHIN_WEEK_HEIGHT DP2PX_VALUE(20)
#define WATCH_PANEL_DOLPHIN_WEEK_WIDTH DP2PX_VALUE(70)

//宇宙飞船 spaceship
#define WATCH_PANEL_SPACESHIP_WEEK_MARGIN_BOTTOM DP2PX_VALUE_Y(56)
#define WATCH_PANEL_SPACESHIP_WEEK_MARGIN_LEFT DP2PX_VALUE(10) // 135
#define WATCH_PANEL_SPACESHIP_WEEK_HEIGHT DP2PX_VALUE(30)
#define WATCH_PANEL_SPACESHIP_WEEK_WIDTH DP2PX_VALUE(70)
#define WATCH_PANEL_SPACESHIP_DATE_MARGIN_BOTTOM DP2PX_VALUE_Y(56)
#define WATCH_PANEL_SPACESHIP_DATE_MARGIN_LEFT DP2PX_VALUE(56)
#define WATCH_PANEL_SPACESHIP_DATE_HEIGHT DP2PX_VALUE(30)
#define WATCH_PANEL_SPACESHIP_DATE_WIDTH DP2PX_VALUE(70)

//太空站表盘
#define WATCH_PANEL_SPACE_STATION_DATE_MARGIN_BOTTOM DP2PX_VALUE_Y(34) //日期屏幕底部边距
#define WATCH_PANEL_SPACE_STATION_DATE_MARGIN_LEFT DP2PX_VALUE(102)  //日期屏幕左边距
#define WATCH_PANEL_SPACE_STATION_DATE_IMG_WIDTH DP2PX_VALUE(14)    //日期图片宽度
#define WATCH_PANEL_SPACE_STATION_DATE_Y MMI_MAINSCREEN_HEIGHT - WATCH_PANEL_SPACE_STATION_DATE_MARGIN_BOTTOM
#define WATCH_PANEL_SPACE_STATION_DATE_START_X WATCH_PANEL_SPACE_STATION_DATE_MARGIN_LEFT
#define WATCH_PANEL_SPACE_STATION_YEAR_START_X DP2PX_VALUE(33)
#define WATCH_PANEL_SPACE_STATION_TIME_IMG_WIDTH DP2PX_VALUE(28)    //时间图片宽度
#define WATCH_PANEL_SPACE_STATION_BATTERY_PERCENT_IMG_WIDTH DP2PX_VALUE(14)
#define WATCH_PANEL_SPACE_STATION_COLON_IMG_WIDTH DP2PX_VALUE(16)
#ifdef MAINLCD_DEV_SIZE_240X284
#define WATCH_PANEL_SPACE_STATION_TIME_MARGIN_TOP 38
#define WATCH_PANEL_SPACE_STATION_TIME_START_X 56
#define WATCH_PANEL_SPACE_STATION_BATTERY_PERCENT_MARGIN_RIGHT 92 //电量百分百
#define WATCH_PANEL_SPACE_STATION_BATTERY_MARGIN_TOP 11
#define WATCH_PANEL_SPACE_STATION_POWER_START_X 83 //电量图标
#define WATCH_PANEL_SPACE_STATION_WEATHER_MARGIN_LEFT 25
#define WATCH_PANEL_SPACE_STATION_WEATHER_ICON_MARGIN_TOP 84
#define WATCH_PANEL_SPACE_STATION_WEATHER_MARGIN_TOP 10
#define WATCH_PANEL_SPACE_STATION_WEATHER_TEMPERATURE_MARGIN_TOP 115 //摄氏度
#define WATCH_PANEL_SPACE_STATION_WEATHER_TEMPERATURE_ICON_START_X 46 //摄氏度
#define WATCH_PANEL_SPACE_STATION_WEATHER_TEMPERATURE_IMG_WIDTH 14    //温度图片宽度
#define WATCH_PANEL_SPACE_STATION_TIME_X_OFFSET 1
#else
#define WATCH_PANEL_SPACE_STATION_TIME_MARGIN_TOP DP2PX_VALUE_Y(38)
#define WATCH_PANEL_SPACE_STATION_TIME_START_X DP2PX_VALUE(56)
#define WATCH_PANEL_SPACE_STATION_BATTERY_PERCENT_MARGIN_RIGHT DP2PX_VALUE(92) //电量百分百
#define WATCH_PANEL_SPACE_STATION_BATTERY_MARGIN_TOP DP2PX_VALUE_Y(11)
#define WATCH_PANEL_SPACE_STATION_POWER_START_X DP2PX_VALUE(83) //电量图标
#define WATCH_PANEL_SPACE_STATION_WEATHER_MARGIN_LEFT DP2PX_VALUE(25)
#define WATCH_PANEL_SPACE_STATION_WEATHER_ICON_MARGIN_TOP DP2PX_VALUE_Y(84)
#define WATCH_PANEL_SPACE_STATION_WEATHER_MARGIN_TOP DP2PX_VALUE_Y(10)
#define WATCH_PANEL_SPACE_STATION_WEATHER_TEMPERATURE_MARGIN_TOP DP2PX_VALUE_Y(115) //摄氏度
#define WATCH_PANEL_SPACE_STATION_WEATHER_TEMPERATURE_ICON_START_X DP2PX_VALUE(46) //摄氏度
#define WATCH_PANEL_SPACE_STATION_WEATHER_TEMPERATURE_IMG_WIDTH DP2PX_VALUE(14)    //温度图片宽度
#define WATCH_PANEL_SPACE_STATION_TIME_X_OFFSET 1
#endif
#define WATCH_PANEL_SPACE_STATION_WEEK_Y DP2PX_VALUE(86)
#define WATCH_PANEL_SPACE_STATION_WEEK_X DP2PX_VALUE(98)

//***********************************************

//***************wechar 微聊************************
#define WECHART_RECORD_IMG_WIDTH DP2PX_VALUE(170)  //按住录音背景宽度
#define WECHART_RECORD_IMG_MARGIN_BOTTOM DP2PX_VALUE(58) //按住录音 top距离底部距离
#define WECHART_RECORD_IMG_X (MMI_MAINSCREEN_WIDTH-WECHART_RECORD_IMG_WIDTH)/2
#define WECHART_RECORD_IMG_Y (MMI_MAINSCREEN_HEIGHT-WECHART_RECORD_IMG_MARGIN_BOTTOM)
#define WECHART_RECORD_TEXT_MARGIN_LEFT DP2PX_VALUE(88)
#define WECHART_RECORD_TEXT_MARGIN_BOTTOM DP2PX_VALUE(5)
#define WECHART_RECORD_TEXT_RECT {WECHART_RECORD_TEXT_MARGIN_LEFT,WECHART_RECORD_IMG_Y,MMI_MAINSCREEN_WIDTH,MMI_MAINSCREEN_HEIGHT-WECHART_RECORD_TEXT_MARGIN_BOTTOM}
#define WECHART_RECORD_COUNTDOWN_TEXT_MARGIN_BOTTOM MMI_MAINSCREEN_HEIGHT-WECHART_RECORD_IMG_MARGIN_BOTTOM
#define WECHART_RECORD_COUNTDOWN_TEXT_RECT {0,WECHART_RECORD_COUNTDOWN_TEXT_MARGIN_BOTTOM,DP2PX_VALUE(40),MMI_MAINSCREEN_HEIGHT} //录音倒计时
//****************************************

//***************拨号盘************************
#if (MMI_MAINSCREEN_WIDTH == 240) && (MMI_MAINSCREEN_HEIGHT == 284)
#define DIAL_NUMBER_START_Y  62
#define DIAL_NUMBER_START_X  9
#define DIAL_NUMBER_IMG_WIDTH  72
#define DIAL_NUMBER_IMG_HEIGHT  38
#define DIAL_NUMBER_MARGIN_X 3
#ifdef MAINLCD_DEV_SIZE_240X284
#define DIAL_NUMBER_MARGIN_Y 13
#else
#define DIAL_NUMBER_MARGIN_Y 3
#endif
#define DIAL_NUMBER_NEXT_X (DIAL_NUMBER_IMG_WIDTH+DIAL_NUMBER_MARGIN_X)
#define DIAL_NUMBER_NEXT_Y (DIAL_NUMBER_IMG_HEIGHT+DIAL_NUMBER_MARGIN_Y)

#define MMIZDT_DIAL_EDIT_FORM_HEIGHT_H DP2PX_VALUE(43)

#elif (MMI_MAINSCREEN_WIDTH == 128) && (MMI_MAINSCREEN_HEIGHT == 128)

#define DIAL_NUMBER_START_Y  DP2PX_VALUE(62)
#define DIAL_NUMBER_START_X  DP2PX_VALUE(5)

#define DIAL_NUMBER_IMG_WIDTH  40
#define DIAL_NUMBER_IMG_HEIGHT  22

#define DIAL_NUMBER_MARGIN_X DP2PX_VALUE(3)
#define DIAL_NUMBER_MARGIN_Y DP2PX_VALUE(3)

#define DIAL_NUMBER_NEXT_X (DIAL_NUMBER_IMG_WIDTH+DIAL_NUMBER_MARGIN_X)
#define DIAL_NUMBER_NEXT_Y (DIAL_NUMBER_IMG_HEIGHT+DIAL_NUMBER_MARGIN_Y)

#define MMIZDT_DIAL_EDIT_FORM_HEIGHT_H DP2PX_VALUE(33)

#endif

#define MMIZDT_DIAL_EDIT_FORM_HEIGHT DP2PX_VALUE(55)//40///140//45 45

#define MMIZDT_DIAL_EDIT_FONT DP_FONT_32

//***********************************************

//*********************************************************
#define WEATHER_SIM_RECT {0,DP2PX_VALUE(200),(MMI_MAINSCREEN_WIDTH -1),MMI_MAINSCREEN_HEIGHT}
#define WEATHER_CITY_RECT {MMI_MAINSCREEN_WIDTH/3,DP2PX_VALUE_Y(10),(MMI_MAINSCREEN_WIDTH -1),DP2PX_VALUE_Y(40)}
#define WEATHER_UPDATE_TIME_RECT {MMI_MAINSCREEN_WIDTH/3,DP2PX_VALUE_Y(169),(MMI_MAINSCREEN_WIDTH -1),DP2PX_VALUE_Y(199)}
#define WEATHER_TEMPERATURE_RECT {DP2PX_VALUE(145),DP2PX_VALUE_Y(110),(MMI_MAINSCREEN_WIDTH -1),DP2PX_VALUE_Y(160)}
#define WEATHER_TEXT_RECT {DP2PX_VALUE(150),DP2PX_VALUE_Y(60),MMI_MAINSCREEN_WIDTH,DP2PX_VALUE_Y(100)}
#define WEATHER_ICON_X DP2PX_VALUE(40)
#define WEATHER_ICON_Y DP2PX_VALUE_Y(60)
//*********************************************************

//**********************计算器***********************************
#define CALC_NUMBER_START_Y  DP2PX_VALUE(65)
#define CALC_NUMBER_START_X  DP2PX_VALUE_Y(7)
#define CALC_NUMBER_IMG_WIDTH  DP2PX_VALUE(55)
#define CALC_NUMBER_IMG_HEIGHT  DP2PX_VALUE_Y(36)
#define CALC_NUMBER_MARGIN_X 2
#ifdef MAINLCD_DEV_SIZE_240X284
#define CALC_NUMBER_MARGIN_Y 14
#else
#define CALC_NUMBER_MARGIN_Y 3
#endif
#define CALC_NUMBER_NEXT_X (CALC_NUMBER_IMG_WIDTH+CALC_NUMBER_MARGIN_X)
#define CALC_NUMBER_NEXT_Y (CALC_NUMBER_IMG_HEIGHT+CALC_NUMBER_MARGIN_Y)
#define CALC_BACKSPACE_MARGIN_RIGHT DP2PX_VALUE(50)
#define CALC_BACKSPACE_IMG_WIDTH DP2PX_VALUE(33)
#define CALC_BACKSPACE_IMG_HEIGHT DP2PX_VALUE_Y(20)
#define CALC_BACKSPACE_TOP DP2PX_VALUE_Y(20)
#define CALC_BACKSPACE_LEFT MMI_MAINSCREEN_WIDTH-CALC_BACKSPACE_MARGIN_RIGHT
#define CALC_BACKSPACE_RIGHT CALC_BACKSPACE_LEFT+CALC_BACKSPACE_IMG_WIDTH
#define CALC_BACKSPACE_BOTTOM CALC_BACKSPACE_TOP+CALC_BACKSPACE_IMG_HEIGHT
#define CALC_BACKSPACE_RECT {CALC_BACKSPACE_LEFT,CALC_BACKSPACE_TOP,CALC_BACKSPACE_RIGHT,CALC_BACKSPACE_BOTTOM}
//************************计算器*********************************

//***************AI 机器人 图灵 ************************
#define AICHAT_RECORD_ANIM_DELAY 500
#define AICHAT_RECORD_ANIMAL_TOTAL_FRAME_NUM  4
#define AI_CHAT_MAX_RECORD_TIME_MS 20000
#define AI_CHAT_RECORD_IMG_WIDTH DP2PX_VALUE(128)
#define AI_CHAT_RECORD_IMG_HEIGHT DP2PX_VALUE_Y(42)
#define AI_CHAT_RECORD_IMG_MARGIN_BOTTOM DP2PX_VALUE(64)
#define AI_CHAT_RECORD_IMG_X (MMI_MAINSCREEN_WIDTH-AI_CHAT_RECORD_IMG_WIDTH)/2
#define AI_CHAT_RECORD_IMG_Y MMI_MAINSCREEN_HEIGHT-AI_CHAT_RECORD_IMG_MARGIN_BOTTOM
#define AI_CHAT_RECORD_TEXT_MARGIN_LEFT DP2PX_VALUE(90)
#define AI_CHAT_RECORD_TEXT_MARGIN_BOTTOM DP2PX_VALUE_Y(16)
#define AI_CHAT_RECORD_TEXT_RECT {AI_CHAT_RECORD_TEXT_MARGIN_LEFT,AI_CHAT_RECORD_IMG_Y,AI_CHAT_RECORD_TEXT_MARGIN_LEFT+AI_CHAT_RECORD_IMG_WIDTH,MMI_MAINSCREEN_HEIGHT-AI_CHAT_RECORD_TEXT_MARGIN_BOTTOM}
#define AI_CHAT_BOTTOM_RECT {0,MMI_MAINSCREEN_HEIGHT-AI_CHAT_RECORD_IMG_MARGIN_BOTTOM,MMI_MAINSCREEN_WIDTH,MMI_MAINSCREEN_HEIGHT}
#define AI_CHAT_TIPS_ICON_POINT DP2PX_POINT(70,47)
#define AI_CHAT_TIPS_TEXT_RECT DP2PX_RECT(32,164,215,225)
#define AI_CHAT_USAGE_TIPS_TEXT_RECT DP2PX_RECT(32,10,220,130)
#define AI_CHAT_TIPS_DELAY 2000
//****************************************

//***************GALLERY 相册 ************************
#define GALLERY_LIST_ITEM_MARGIN_SPACE DP2PX_RECT(30,10,10,10)
#define GALLERY_LIST_ITEM_ICON_WIDTH DP2PX_VALUE(80)
#define GALLERY_LIST_ITEM_ICON_HEIGHT DP2PX_VALUE(80)
#define GALLERY_LIST_MARGIN_BOTTOM DP2PX_VALUE(20) //列表距离底部边距
#define GALLERY_PICK_LIST_MARGIN_BOTTOM DP2PX_VALUE_Y(40)
#define GALLERY_PICK_BUTTON_WIDTH DP2PX_VALUE(80) //取消、删除按钮宽度
#define GALLERY_PICK_BUTTON_HEIGHT DP2PX_VALUE_Y(40) 
#define GALLERY_PICK_BUTTON_LEFT_RIGHT_MARGIN DP2PX_VALUE(25) //取消、删除按钮左右边距
#define GALLERY_PICK_BUTTON_MARGIN_TOP_BOTTOM DP2PX_VALUE_Y(10) //取消、删除按钮距离底部边距

#define GALLERY_PICK_BUTTON_TOP MMI_MAINSCREEN_HEIGHT - GALLERY_PICK_BUTTON_MARGIN_TOP_BOTTOM - GALLERY_PICK_BUTTON_HEIGHT
#define GALLERY_PICK_CANEL_BUTTON_RIGHT GALLERY_PICK_BUTTON_LEFT_RIGHT_MARGIN+GALLERY_PICK_BUTTON_WIDTH

#define GALLERY_PICK_DELETE_ICON_OFFSET DP2PX_VALUE(21)
#if defined(ZTE_SUPPORT_240X284)||defined(MAINLCD_DEV_SIZE_240X284)
#define GALLERY_ICONLIST_RECT 		{0, 40, 239, 260}
#define GALLERY_ICONLIST_MARK_RECT 	{0, 40, 239, 220}
#define GALLERY_PICK_DELETE_RECT 	{124, 223, 228, 265}
#define GALLERY_PICK_CANEL_RECT 	{12, 223, 116, 265}
#else
#define GALLERY_ICONLIST_RECT 		DP2PX_RECT(0, 40, 239, 230)
#define GALLERY_ICONLIST_MARK_RECT 	DP2PX_RECT(0, 40, 239, 190)
#define GALLERY_PICK_DELETE_RECT 	DP2PX_RECT(124, 193, 228, 235)
#define GALLERY_PICK_CANEL_RECT 	DP2PX_RECT(12, 193, 116, 235)
#endif
//****************************************************

#define CHARGING_ANIMATION_RECT {50,68,90,100}

#ifdef __cplusplus
    }
#endif

#endif
