//duerapp home page related id, included by duerapp_id.h

//for test
MMI_DUERAPP_HOME_TEST_FORM_CTRL_ID,
MMI_DUERAPP_HOME_TEST_TXT_CTRL_ID,



//for homepage
MMI_DUERAPP_MAIN_FORM_CTRL_ID,
MMI_DUERAPP_HOME_FORM_CTRL_ID,
MMI_DUERAPP_HOME_TITLE_FORM_CTRL_ID,
MMI_DUERAPP_HOME_TITLE_BUTTON_CTRL_ID,
MMI_DUERAPP_HOME_TITLE_LABEL_CTRL_ID,
MMI_DUERAPP_HOME_HINT_LABEL_CTRL_ID,
MMI_DUERAPP_HOME_PLAYER_FORM_CTRL_ID,
MMI_DUERAPP_HOME_MUSIC_ENTER_CTRL_ID,
MMI_DUERAPP_HOME_LIST_CTRL_ID,

MMI_DUERAPP_HOME_SLIDE_POINT_BUTTON_CTRL_ID,
MMI_DUERAPP_TEST_SLIDE_POINT_BUTTON_CTRL_ID,

MMI_DUERAPP_TEST_ENGI_FORM_CTRL_ID,
MMI_DUERAPP_TEST_ENGI_1_BUTTON_CTRL_ID,
MMI_DUERAPP_TEST_ENGI_2_BUTTON_CTRL_ID,

#define MMI_DUERAPP_BANNER_GROUP_ID(_page, _n)      MMI_DUERAPP_##_page##_BANNER_FORM##_n##_CTRL_ID, \
                                                    MMI_DUERAPP_##_page##_BANNER_ANIM##_n##_CTRL_ID, \
                                                    MMI_DUERAPP_##_page##_BANNER_LABEL##_n##_CTRL_ID

#define MMI_DUERAPP_SKILL_GROUP_ID(_page, _n)       MMI_DUERAPP_##_page##_SKILL_ICON_FORM##_n##_CTRL_ID, \
                                                    MMI_DUERAPP_##_page##_SKILL_ANIM##_n##_1_CTRL_ID, \
                                                    MMI_DUERAPP_##_page##_SKILL_ANIM##_n##_2_CTRL_ID, \
                                                    MMI_DUERAPP_##_page##_SKILL_LABEL_FORM##_n##_CTRL_ID, \
                                                    MMI_DUERAPP_##_page##_SKILL_LABEL##_n##_1_CTRL_ID, \
                                                    MMI_DUERAPP_##_page##_SKILL_LABEL##_n##_2_CTRL_ID

MMI_DUERAPP_BANNER_GROUP_ID(HOME, 1),
MMI_DUERAPP_HOME_SKILL_TITLE1_CTRL_ID,
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 1),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 2),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 3),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 4),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 5),

MMI_DUERAPP_BANNER_GROUP_ID(HOME, 2),
MMI_DUERAPP_HOME_SKILL_TITLE2_CTRL_ID,
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 6),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 7),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 8),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 9),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 10),

MMI_DUERAPP_BANNER_GROUP_ID(HOME, 3),
MMI_DUERAPP_HOME_SKILL_TITLE3_CTRL_ID,
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 11),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 12),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 13),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 14),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 15),

MMI_DUERAPP_BANNER_GROUP_ID(HOME, 4),
MMI_DUERAPP_HOME_SKILL_TITLE4_CTRL_ID,
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 16),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 17),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 18),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 19),
MMI_DUERAPP_SKILL_GROUP_ID(HOME, 20),




