//[[define image information

RES_ADD_IMG(IMAGE_DUERAPP_PREPARE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_PREPARE.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_PAUSE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_PAUSE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_PLAY,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_PLAY.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_PROGRESS,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_PROGRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_PREVIOUS,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_PREVIOUS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_NEXT,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_NEXT.png",IMG_CMP_PNG_ARGB_RLE,0)
//RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_BG,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_START,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_START.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_DUERAPP_PROTOCOL,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_PROTOCOL.jpg",IMG_CMP_JPG_SCI,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_DANCE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_DANCE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_VOLUME_0,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_VOLUME_0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_VOLUME_1,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_VOLUME_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_VOLUME_2,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_VOLUME_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_VOLUME_3,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_VOLUME_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_VOLUME_4,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_VOLUME_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_VOLUME_MINUS,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_VOLUME_MINUS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_VOLUME_PLUS,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_VOLUME_PLUS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_VOLUME_MINUS_PRESS,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_VOLUME_MINUS_PRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_VOLUME_PLUS_PRESS,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_VOLUME_PLUS_PRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image information
RES_ADD_IMG(IMAGE_DUERAPP_QR_FRAME,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_QR_FRAME.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_DUERAPP_CENTER_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_CENTER_TAG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_INIF_TAG,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_INIF_TAG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_XIAODU,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_XIAODU.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_DICTIONARY_ICON,"\\MMI_RES_##\\IMAG\\res_launcher_ic_dictionary34.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_INTERPRETER_ICON,"\\MMI_RES_##\\IMAG\\res_launcher_ic_Interpreter34.png",IMG_CMP_PNG_ARGB_RLE,0)

//[[define anim infomation
// RES_ADD_IMG(IMAGE_DUERAPP_PREPARE_ANIM,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_PREPARE_ANIM.gif",IMG_CMP_GIF_SCI,0)
// RES_ADD_IMG(IMAGE_DUERAPP_LISTENING_ANIM,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_LISTENING_ANIM.gif",IMG_CMP_GIF_SCI,0)
// RES_ADD_IMG(IMAGE_DUERAPP_THINKING_ANIM,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_THINKING_ANIM.gif",IMG_CMP_GIF_SCI,0)
RES_ADD_IMG(IMAGE_DUERAPP_PREPARE_ANIM,"\\MMI_RES_##\\IMAG\\static_xiaodu_prepare.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_LISTENING_ANIM,"\\MMI_RES_##\\IMAG\\static_xiaodu_listening.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_THINKING_ANIM,"\\MMI_RES_##\\IMAG\\static_xiaodu_thinking.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define anim infomation



//[[define string information
//list test
RES_ADD_STRING(TXT_DUERAPP_TITLE,"Xiaodu")
//]]define string information

RES_ADD_IMG(IMAGE_DUERAPP_LESSON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_LESSON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_FUNCTION_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_FUNCTION_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_STORY_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_STORY_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_VIP_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_VIP_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_BUTTON_ICON,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_BUTTON_ICON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_VIP_TAB,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_VIP_TAB.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MIGU_BG,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MIGU_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_CLOSE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_CLOSE.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_COLLECT,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_COLLECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_COLLECTED,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_COLLECTED.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_LIST,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_LIST.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_ANIM_CIRCLE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_ANIM_CIRCLE.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUER_IC_POINT_OFF,"\\MMI_RES_##\\IMAG\\IMAGE_DUER_IC_POINT_OFF.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUER_IC_POINT_ON,"\\MMI_RES_##\\IMAG\\IMAGE_DUER_IC_POINT_ON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_TITLE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_TITLE.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_DUERAPP_WRITING_NARRATIVE,        "\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_WRITING_NARRATIVE.png",      IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_DUERAPP_WRITING_ARGUMENTATION,    "\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_WRITING_ARGUMENTATION.png",  IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_DUERAPP_WRITING_THOUGHTS,         "\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_WRITING_THOUGHTS.png",       IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_DUERAPP_WRITING_LETTER,           "\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_WRITING_LETTER.png",         IMG_CMP_PNG_ARGB_RLE, 0)

RES_ADD_IMG(IMAGE_DUERAPP_WRITING_SETTINGS, "\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_WRITING_SETTINGS.png",   IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_DUERAPP_WRITING_FILTER,   "\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_WRITING_FILTER.png",     IMG_CMP_PNG_ARGB_RLE, 0)
RES_ADD_IMG(IMAGE_DUERAPP_BANNER1,          "\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_BANNER1.png",            IMG_CMP_PNG_ARGB_RLE, 0)

RES_ADD_IMG(IMAGE_DUERAPP_MUSIC_ENTER,      "\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_MUSIC_ENTER.png",        IMG_CMP_PNG_ARGB_RLE, 0)



RES_ADD_IMG(IMAGE_DUERAPP_CENTER_CONTACT_US,"\\MMI_RES_##\\IMAG\\IMAGE_DUER_CENTER_CONTACT_US.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_CENTER_ABOUT_XIAODU,"\\MMI_RES_##\\IMAG\\IMAGE_DUER_CENTER_ABOUT_XIAODU.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_CENTER_BANNER,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_CENTER_BANNER.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_CENTER_BUTTER_BG,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_CENTER_BUTTER_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_CENTER_ABOUT_XIAODU_BIG,"\\MMI_RES_##\\IMAG\\IMAGE_DUER_CENTER_ABOUT_XIAODU_BIG.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_DUERAPP_RECT_ICON_LOAD,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_RECT_ICON_LOAD.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_ROUND_ICON_LOAD,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_ROUND_ICON_LOAD.png",IMG_CMP_PNG_ARGB_RLE,0)

RES_ADD_IMG(IMAGE_DUERAPP_NO_NETWORK,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_NO_NETWORK.png",IMG_CMP_PNG_ARGB_RLE,0)

// /********* duer input start *********/
// //[[define anim infomation
// RES_ADD_IMG(IMAGE_DUERINPUT_PREPARE_ANIM,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_PREPARE_ANIM.gif",IMG_CMP_GIF_SCI,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_LISTEN_ANIM,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_LISTEN_ANIM.gif",IMG_CMP_GIF_SCI,0)
// //]]define anim infomation
// RES_ADD_IMG(IMAGE_DUERINPUT_REBACK,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_REBACK.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_CONFIRM,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_CONFIRM.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_BACKSPACE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_BACKSPACE.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_VOICE_BG,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_VOICE_BG.png",IMG_CMP_PNG_ARGB_RLE,0)

// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_SELECT,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_SELECT.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_BUTTON_PRESS,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_BUTTON_PRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_BUTTON_RELEASE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_BUTTON_RELEASE.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_UPPER_BUTTON_PRESS,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_UPPER_BUTTON_PRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_UPPER_BUTTON_RELEASE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_UPPER_BUTTON_RELEASE.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_SPACE_BUTTON_PRESS,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_SPACE_BUTTON_PRESS.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_SPACE_BUTTON_RELEASE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_SPACE_BUTTON_RELEASE.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_VOICE_BG,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_VOICE_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_OTHER_BG,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_OTHER_BG.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_VOICE_PRE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_VOICE_PRE.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_VOICE_REL,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_VOICE_REL.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_LETTER_PRE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_LETTER_PRE.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_LETTER_REL,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_LETTER_REL.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_NUMBER_PRE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_NUMBER_PRE.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_NUMBER_REL,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_NUMBER_REL.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_CHARCTER_PRE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_CHARCTER_PRE.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_CHARCTER_REL,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_CHARCTER_REL.png",IMG_CMP_PNG_ARGB_RLE,0)
// /********* duer input end *********/

//slide add
RES_ADD_IMG(IMAGE_DUER_IC_POINT_1_OF_3,"\\MMI_RES_##\\IMAG\\IMAGE_DUER_IC_POINT_1_OF_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUER_IC_POINT_2_OF_3,"\\MMI_RES_##\\IMAG\\IMAGE_DUER_IC_POINT_2_OF_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUER_IC_POINT_3_OF_3,"\\MMI_RES_##\\IMAG\\IMAGE_DUER_IC_POINT_3_OF_3.png",IMG_CMP_PNG_ARGB_RLE,0)

//dictionary
RES_ADD_IMG(IMAGE_DUERAPP_DICTIONARY_WORD_BG_BIG,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_DICTIONARY_WORD_BG_BIG.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_DICTIONARY_WORD_BG_NORMAL,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_DICTIONARY_WORD_BG_NORMAL.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_DICTIONARY_PINYIN_VOICE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_DICTIONARY_PINYIN_VOICE.png",IMG_CMP_PNG_ARGB_RLE,0)

//xiaodu assists
RES_ADD_IMG(IMAGE_DUERAPP_TRUMPET_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_TRUMPET_BUTTON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_ASSISTS_SELECT,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_ASSISTS_SELECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_ASSISTS_UNSELECT,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_ASSISTS_UNSELECT.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_ASSISTS_EDIT_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_ASSISTS_EDIT_BUTTON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_ASSISTS_SEND_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_ASSISTS_SEND_BUTTON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_ASSISTA_APPLY_BUTTON,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_ASSISTA_APPLY_BUTTON.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMAGE_DUERAPP_ASSISTS_INPUT_MIC,"\\MMI_RES_##\\IMAG\\IMAGE_DUERAPP_ASSISTS_INPUT_MIC.png",IMG_CMP_PNG_ARGB_RLE,0)

// duer pinyin input 
// RES_ADD_IMG(IMAGE_DUERINPUT_DOWN_TRIANGLE, "\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_DOWN_TRIANGLE.png", IMG_CMP_PNG_ARGB_RLE, 0)
// RES_ADD_IMG(IMAGE_DUERINPUT_UP_TRIANGLE, "\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_UP_TRIANGLE.png", IMG_CMP_PNG_ARGB_RLE, 0)
// RES_ADD_IMG(IMAGE_DUERINPUT_PINYIN_RES_BUTTON_PRESS, "\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_PINYIN_RES_BUTTON_PRESS.png", IMG_CMP_PNG_ARGB_RLE, 0) 
// RES_ADD_IMG(IMAGE_DUERINPUT_PINYIN_RES_BUTTON_RELEASE, "\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_PINYIN_RES_BUTTON_RELEASE.png", IMG_CMP_PNG_ARGB_RLE, 0) 
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_PINYIN_PRE,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_PINYIN_PRE.png",IMG_CMP_PNG_ARGB_RLE,0)
// RES_ADD_IMG(IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_PINYIN_REL,"\\MMI_RES_##\\IMAG\\IMAGE_DUERINPUT_ICON_RES_INPUT_SELECT_PINYIN_REL.png",IMG_CMP_PNG_ARGB_RLE,0)