/*****************************************************************************
******************************************************************************                           *
******************************************************************************/

#ifndef _DUERAPP_ID_H_
#define _DUERAPP_ID_H_ 

/**--------------------------------------------------------------------------*
 **                         Include Files                                    *
 **--------------------------------------------------------------------------*/
#include "sci_types.h"
#include "os_api.h"
#include "mmk_type.h"
#include "mmi_module.h"

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef __cplusplus
    extern   "C"
    {
#endif

/**--------------------------------------------------------------------------*
 **                         MACRO DEFINITION                                 *
 **--------------------------------------------------------------------------*/


/**--------------------------------------------------------------------------*
 **                         TYPE AND CONSTANT                                *
 **--------------------------------------------------------------------------*/

#define WIN_ID_DEF(win_id) win_id
// window ID
typedef enum
{
    DUERAPP_WIN_ID_START = (MMI_MODULE_DUER << 16),
#include "duerapp_id.def"
    DUERAPP_MAX_WIN_ID
} DUERAPP_WINDOW_ID_E;

#undef WIN_ID_DEF

// control ID
typedef enum
{
    DUERAPP_CTRL_ID_ID_START = DUERAPP_MAX_WIN_ID,
    
    MMI_DUERAPP_CTRL_1_ID, // 可用于任何一个控件测试
    MMI_DUERAPP_CTRL_2_ID, // 可用于任何一个控件测试
    MMI_DUERAPP_CTRL_3_ID, // 可用于任何一个控件测试
    MMI_DUERAPP_CTRL_4_ID, // 可用于任何一个控件测试
    
    MMI_DUERAPP_MENU_CTRL_ID,
    MMI_DUERAPP_LIST_CTRL_ID,
    MMI_DUERAPP_TEXTBOX_CTRL_ID,
    MMI_DUERAPP_BUTTON_CTRL_ID,
    MMI_DUERAPP_BUTTON2_CTRL_ID,
    MMI_DUERAPP_BUTTON_LABEL1_CTRL_ID,
    MMI_DUERAPP_BUTTON_LABEL2_CTRL_ID,

    // main
    MMI_DUERAPP_LABEL_CTRL_ID,
    MMI_DUERAPP_QUERY_TITLE_LABEL_CTRL_ID,
    MMI_DUERAPP_QUERY_LABEL_CTRL_ID_1,
    MMI_DUERAPP_QUERY_LABEL_CTRL_ID_2,
    MMI_DUERAPP_REMIND_LABEL_CTRL_ID,
    MMI_DUERAPP_MUSIC_ENTER_BUTTON_CTRL_ID,
    MMI_DUERAPP_CENTER_BUTTON_CTRL_ID,

    // standard 卡片
    MMI_DUERAPP_RENDER_CARD_FORM_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_ANIM_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_TEXT_CTRL_ID,

    // list 卡片
    MMI_DUERAPP_RENDER_CARD_LIST_FORM_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORM1_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORM2_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORM3_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORM4_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORM5_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORM6_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORM7_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORM8_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORM9_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORM10_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM1_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM2_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM3_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM4_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM5_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM6_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM7_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM8_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM9_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM10_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM11_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM12_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM13_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM14_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM15_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM16_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM17_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM18_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM19_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_FORMX_FORM20_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM1_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM2_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM3_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM4_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM5_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM6_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM7_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM8_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM9_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM10_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM11_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM12_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM13_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM14_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM15_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM16_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM17_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM18_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM19_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_ANIM20_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE1_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE2_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE3_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE4_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE5_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE6_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE7_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE8_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE9_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE10_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE11_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE12_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE13_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE14_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE15_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE16_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE17_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE18_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE19_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_TITLE20_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT1_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT2_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT3_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT4_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT5_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT6_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT7_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT8_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT9_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT10_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT11_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT12_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT13_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT14_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT15_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT16_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT17_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT18_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT19_CTRL_ID,
    MMI_DUERAPP_RENDER_CARD_LIST_CONTENT20_CTRL_ID,

    // 个人中心
    // 中心卡片
    MMI_DUERAPP_CENTER_HOME_FORM_CTRL_ID,
    MMI_DUERAPP_CENTER_SLIDE_POINT_BUTTON_CTRL_ID,

    MMI_DUERAPP_CENTER_HOME_FORM2_CTRL_ID,//for banner
    MMI_DUERAPP_CENTER_HOME_FORM3_CTRL_ID,//for quit
    MMI_DUERAPP_CENTER_LABEL1_CTRL_ID,
    MMI_DUERAPP_CENTER_LABEL2_CTRL_ID,
    MMI_DUERAPP_CENTER_LABEL3_CTRL_ID,
    MMI_DUERAPP_CENTER_BUTTON1_CTRL_ID,
    MMI_DUERAPP_CENTER_BUTTON2_CTRL_ID,
    MMI_DUERAPP_CENTER_BANNER_ANIM_CTRL_ID,
    MMI_DUERAPP_CENTER_HOME_LIST_CTRL_ID,
    MMI_DUERAPP_CENTER_CONTACT_US_BUTTON_CTRL_ID,
    MMI_DUERAPP_CENTER_ABOUT_XIAODU_BUTTON_CTRL_ID,
    
    //联系我们
    MMI_DUERAPP_CONTACT_US_FORM_CTRL_ID,
    MMI_DUERAPP_CONTACT_TEXT_CTRL_ID,
    MMI_DUERAPP_CENTER_WEIXIN_BUTTON_CTRL_ID,

    //关于小度
    MMI_DUERAPP_ABOUT_XIAODU_FORM_CTRL_ID,
    MMI_DUERAPP_ABOUT_XIAODU_FORM1_CTRL_ID,
    MMI_DUERAPP_ABOUT_XIAODU_BUTTON_CTRL_ID,
    MMI_DUERAPP_ABOUT_XIAODU_TEXT1_CTRL_ID,
    MMI_DUERAPP_ABOUT_XIAODU_TEXT2_CTRL_ID,
    MMI_DUERAPP_ABOUT_XIAODU_TEXT3_CTRL_ID,

    // 会员福利
    MMI_DUERAPP_CENTER_VIP_LABEL_CTRL_ID,
    MMI_DUERAPP_CENTER_VIP_BUTTON1_CTRL_ID,
    MMI_DUERAPP_CENTER_VIP_BUTTON2_CTRL_ID,
    MMI_DUERAPP_CENTER_VIP_BUTTON3_CTRL_ID,
    // 反馈页
    MMI_DUERAPP_CENTER_RICHTEXT_CTRL_ID,
    MMI_DUERAPP_QUIT_FORM_CTRL_ID,
    MMI_DUERAPP_QUIT_LABEL_CTRL_ID,
    MMI_DUERAPP_QUIT_TEXT_CTRL_ID,
    MMI_DUERAPP_QUIT_CANCEL_BUTTON_CTRL_ID,
    MMI_DUERAPP_QUIT_OK_BUTTON_CTRL_ID,
    MMI_DUERAPP_CENTER_QUIT_LABEL5_CTRL_ID,
    MMI_DUERAPP_CENTER_QUIT_LABEL6_CTRL_ID,
 
    MMI_DUERAPP_CENTER_QUIT_BUTTON_CTRL_ID,
    // 技能列表
    MMI_DUERAPP_CENTER_SKILL_LIST_CTRL_ID,
    MMI_DUERAPP_CENTER_LISTBOX_CTRL_ID,

    // music
    MMI_DUERAPP_MUSIC_TITLE_LABEL_CTRL_ID,
    MMI_DUERAPP_MUSIC_AUTHOR_LABEL_CTRL_ID,
    MMI_DUERAPP_MUSIC_PREVIOUS_BUTTON_CTRL_ID,
    MMI_DUERAPP_MUSIC_NEXT_BUTTON_CTRL_ID,
    MMI_DUERAPP_MUSIC_PLAY_BUTTON_CTRL_ID,
    MMI_DUERAPP_MUSIC_VIP_BUTTON_CTRL_ID,

    MMI_DUERAPP_MUSIC_PLAY_LIST_BUTTON_CTRL_ID,
    MMI_DUERAPP_MUSIC_COLLECTION_BUTTON_CTRL_ID,
    MMI_DUERAPP_MUSIC_MINUS_BUTTON_CTRL_ID,
    MMI_DUERAPP_MUSIC_PLUS_BUTTON_CTRL_ID,
    MMI_DUERAPP_MUSIC_PLAY_LIST_ANIM_CTRL_ID,
    MMI_DUERAPP_MUSIC_PLAY_CIRCLE_ANIM_CTRL_ID,

    MMI_DUERAPP_MPLAYER_LIST_CTRL_ID,
    // welcome
    MMI_DUERAPP_PROTOCOL_LABEL_CTRL_ID,
    MMI_DUERAPP_PROTOCOL_BUTTON_CTRL_ID,
    MMI_DUERAPP_PROTOCOL_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_START_BUTTON_CTRL_ID,
    MMI_DUERAPP_PROTOCOL_TXT_CTRL_ID,
    MMI_DUERAPP_PROTOCOL_RICHTEXT_CTRL_ID,

    // login
    MMI_DUERAPP_LOGIN_TIPS_CTRL_ID,

    // operate
    MMI_DUERAPP_OPERATE_FORM_CTRL_ID,
    MMI_DUERAPP_OPERATE_IMAGE_CTRL_ID,
    MMI_DUERAPP_OPERATE_CLICK_CTRL_ID,
    MMI_DUERAPP_OPERATE_TITLE_CTRL_ID,
    MMI_DUERAPP_OPERATE_SUBTITLE_CTRL_ID,
    MMI_DUERAPP_OPERATE_IMG_ANIM_CTRL_ID,
    MMI_DUERAPP_OPERATE_IMG_BUTTON_CTRL_ID,
    MMI_DUERAPP_OPERATE_CLOSE_BUTTON_CTRL_ID,
    MMI_DUERAPP_OPERATE_CONTENT_CTRL_ID,
    MMI_DUERAPP_MIGU_PIC_BUTTON_CTRL_ID,
    MMI_DUERAPP_MIGU_CLOSE_BUTTON_CTRL_ID,
    MMI_DUERAPP_OP_LONGPIC_FORM_CTRL_ID,
    MMI_DUERAPP_OP_LONGPIC_IMG_ANIM_CTRL_ID,
    MMI_DUERAPP_OP_LONGPIC_CLICK_BUTTON_CTRL_ID,
    MMI_DUERAPP_OP_COM_QR_CONTENT_CTRL_ID,

    MMI_DUERAPP_ANIM_CTRL_ID,
    MMI_DUERAPP_ICONLIST_CTRL_ID,
    MMI_DUERAPP_ICONLIST_LABEL_CTRL_ID,

    MMI_DUERAPP_SETLIST_CTRL_ID,

    // Writing grade win
    MMI_DUERAPP_WRITING_LABEL_CTRL_ID,
    MMI_DUERAPP_WRITING_GRADE1_CTRL_ID,
    MMI_DUERAPP_WRITING_GRADE2_CTRL_ID,
    MMI_DUERAPP_WRITING_GRADE3_CTRL_ID,
    MMI_DUERAPP_WRITING_GRADE4_CTRL_ID,
    MMI_DUERAPP_WRITING_GRADE5_CTRL_ID,
    MMI_DUERAPP_WRITING_GRADE6_CTRL_ID,
    MMI_DUERAPP_WRITING_GRADE7_CTRL_ID,
    MMI_DUERAPP_WRITING_GRADE8_CTRL_ID,
    MMI_DUERAPP_WRITING_GRADE9_CTRL_ID,
    
    // Writing main win
    MMI_DUERAPP_WRITING_MAIN_FORM1_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_FORM1_1_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_FORM1_2_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_FORM1_2_1_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_FORM1_2_2_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_FORM1_3_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_FORM1_3_1_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_FORM1_3_2_CTRL_ID,
    
    MMI_DUERAPP_WRITING_MAIN_LABEL1_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_LABEL2_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_LABEL3_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_LABEL4_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_LABEL5_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_LABEL6_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_LABEL7_CTRL_ID,
    
    MMI_DUERAPP_WRITING_MAIN_BTN1_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN2_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN3_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN4_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN5_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN6_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN7_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN8_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN9_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN10_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN11_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN12_CTRL_ID,
    MMI_DUERAPP_WRITING_MAIN_BTN13_CTRL_ID,

    // Writing list win
    MMI_DUERAPP_WRITING_LIST_FORM1_CTRL_ID,
    MMI_DUERAPP_WRITING_LIST_LABEL1_CTRL_ID,
    MMI_DUERAPP_WRITING_LIST_LIST_CTRL_ID,

    // Writing filter win
    MMI_DUERAPP_WRITING_FILTER_LABEL_CTRL_ID,
    MMI_DUERAPP_WRITING_FILTER_WALL_CTRL_ID,
    MMI_DUERAPP_WRITING_FILTER_W200_CTRL_ID,
    MMI_DUERAPP_WRITING_FILTER_W400_CTRL_ID,
    MMI_DUERAPP_WRITING_FILTER_W600_CTRL_ID,
    MMI_DUERAPP_WRITING_FILTER_W800_CTRL_ID,
    MMI_DUERAPP_WRITING_FILTER_W1000_CTRL_ID,

    // Writing VIP win
    MMI_DUERAPP_WRITING_VIP_LABEL1_CTRL_ID,
    MMI_DUERAPP_WRITING_VIP_LABEL2_CTRL_ID,
    MMI_DUERAPP_WRITING_VIP_LABEL3_CTRL_ID,
    MMI_DUERAPP_WRITING_VIP_LABEL4_CTRL_ID,
    MMI_DUERAPP_WRITING_VIP_RICHTEXT_CTRL_ID,
    MMI_DUERAPP_WRITING_VIP_BTN1_CTRL_ID,

    // Writing TRIAL win
    MMI_DUERAPP_WRITING_TRIAL_LABEL1_CTRL_ID,
    MMI_DUERAPP_WRITING_TRIAL_LABEL2_CTRL_ID,
    MMI_DUERAPP_WRITING_TRIAL_LABEL3_CTRL_ID,
    MMI_DUERAPP_WRITING_TRIAL_BTN1_CTRL_ID,

    // Writing content win
    MMI_DUERAPP_WRITING_CONTENT_LABEL1_CTRL_ID,
    MMI_DUERAPP_WRITING_CONTENT_TEXT1_CTRL_ID,
    MMI_DUERAPP_WRITING_CONTENT_BTN1_CTRL_ID,

    // no network win
    MMI_DUERAPP_NETWORK_TITLE_CTRL_ID,
    MMI_DUERAPP_NETWORK_SUBTITLE_CTRL_ID,

    //小度词典测试-组词
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM1_CTRL_ID,//两行-标题FORM
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_CTRL_ID,//两行-按钮组FORM
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORM1_CTRL_ID,//两列FORM
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORM2_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM1_LABEL_CTRL_ID,//组词-标题
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON1_CTRL_ID,//组词-按钮，最大15个按钮
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON2_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON3_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON4_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON5_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON6_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON7_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON8_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON9_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON10_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON11_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON12_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON13_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON14_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_GROUPWORDS_FORM2_FORMX_BUTTON15_CTRL_ID,

    //小度词典测试-单字
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_CTRL_ID,//词结构
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM2_CTRL_ID,//释义
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM3_CTRL_ID,//反义词
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM4_CTRL_ID,//近义词
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM5_CTRL_ID,//组词
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM6_CTRL_ID,//造句
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_IMGTXTBUTTON_CTRL_ID,//词结构-单字信息
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_CTRL_ID,//字、拼音(喇叭)FORM
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM2_CTRL_ID,//部首、笔画、结构的FORM
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM1_CTRL_ID,//字FORM
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_CTRL_ID,//拼音(喇叭)FORM
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_FORM1_CTRL_ID,//成对包裹拼音和喇叭的FORM
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_FORM2_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_FORM3_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_FORM4_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_FORM5_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_FORM6_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_LABEL1_CTRL_ID,//词结构-拼音CTRL及对应图片按钮CTRL，目前6个
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_LABEL2_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_LABEL3_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_LABEL4_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_LABEL5_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_LABEL6_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_BUTTON1_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_BUTTON2_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_BUTTON3_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_BUTTON4_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_BUTTON5_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM1_FORM2_PINYIN_BUTTON6_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM1_FORM2_TEXTBOX1_CTRL_ID,//词结构-内容展示，部首、笔画、结构、繁体字等
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM2_TITLE_LABEL_CTRL_ID,//释义-标题
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM2_TEXTBOX1_CTRL_ID,//释义-内容
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM3_TITLE_LABEL_CTRL_ID,//反义词-标题
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM3_TEXTBOX1_CTRL_ID,//反义词-内容
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM4_TITLE_LABEL_CTRL_ID,//近义词-标题
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM4_TEXTBOX1_CTRL_ID,//近义词-内容
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM5_TITLE_LABEL_CTRL_ID,//组词-标题
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM5_TEXTBOX1_CTRL_ID,//组词-内容
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM6_TITLE_LABEL_CTRL_ID,//造句-标题
    MMI_DUERAPP_DICTIONARY_SINGLE_FORM6_TEXTBOX1_CTRL_ID,//造句-内容

    //小度词典测试-多字
    MMI_DUERAPP_DICTIONARY_MULTI_FORM_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_CTRL_ID,//词结构
    MMI_DUERAPP_DICTIONARY_MULTI_FORM2_CTRL_ID,//释义
    MMI_DUERAPP_DICTIONARY_MULTI_FORM3_CTRL_ID,//反义词
    MMI_DUERAPP_DICTIONARY_MULTI_FORM4_CTRL_ID,//近义词
    MMI_DUERAPP_DICTIONARY_MULTI_FORM5_CTRL_ID,//组词
    MMI_DUERAPP_DICTIONARY_MULTI_FORM6_CTRL_ID,//造句
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_CTRL_ID,//字群FORM-目前最多15字
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM2_CTRL_ID,//拼音(喇叭)FORM
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON1_CTRL_ID,//词结构-多字字信息
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON2_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON3_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON4_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON5_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON6_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON7_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON8_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON9_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON10_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON11_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON12_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON13_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON14_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_IMGTXTBUTTON15_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM2_TEXTBOX_CTRL_ID,//拼音
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM2_IMGTXTBUTTON_CTRL_ID,//喇叭
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_FORM1_CTRL_ID,//字FORM-三列
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_FORM2_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM1_FORM1_FORM3_CTRL_ID,
    MMI_DUERAPP_DICTIONARY_MULTI_FORM2_TITLE_LABEL_CTRL_ID,//释义-标题
    MMI_DUERAPP_DICTIONARY_MULTI_FORM2_TEXTBOX1_CTRL_ID,//释义-内容
    MMI_DUERAPP_DICTIONARY_MULTI_FORM3_TITLE_LABEL_CTRL_ID,//反义词-标题
    MMI_DUERAPP_DICTIONARY_MULTI_FORM3_TEXTBOX1_CTRL_ID,//反义词-内容
    MMI_DUERAPP_DICTIONARY_MULTI_FORM4_TITLE_LABEL_CTRL_ID,//近义词-标题
    MMI_DUERAPP_DICTIONARY_MULTI_FORM4_TEXTBOX1_CTRL_ID,//近义词-内容
    MMI_DUERAPP_DICTIONARY_MULTI_FORM5_TITLE_LABEL_CTRL_ID,//组词-标题
    MMI_DUERAPP_DICTIONARY_MULTI_FORM5_TEXTBOX1_CTRL_ID,//组词-内容
    MMI_DUERAPP_DICTIONARY_MULTI_FORM6_TITLE_LABEL_CTRL_ID,//造句-标题
    MMI_DUERAPP_DICTIONARY_MULTI_FORM6_TEXTBOX1_CTRL_ID,//造句-内容

    //会员界面扫码及编辑
    MMI_DUERAPP_ASSISTS_FORM_CTRL_ID,
    MMI_DUERAPP_ASSISTS_FORM1_CTRL_ID,
    MMI_DUERAPP_ASSISTS_FORM2_CTRL_ID,
    MMI_DUERAPP_ASSISTS_FORM1_FORM1_CTRL_ID,//喇叭和喊爸妈来助力LABEL
    MMI_DUERAPP_ASSISTS_FORM1_FORM2_CTRL_ID,
    MMI_DUERAPP_ASSISTS_FORM1_FORM1_IMAGE_CTRL_ID,//喇叭图片
    MMI_DUERAPP_ASSISTS_FORM1_FORM1_LABEL_CTRL_ID,//喊爸妈助力
    MMI_DUERAPP_ASSISTS_FORM1_FORM2_LABEL_CTRL_ID,//编辑助力内容发给家长
    MMI_DUERAPP_ASSISTS_FORM1_FORM2_BUTTON_CTRL_ID,//编辑按钮
    MMI_DUERAPP_ASSISTS_FORM2_FORM1_CTRL_ID,//喇叭和喊爸妈来扫码LABEL
    MMI_DUERAPP_ASSISTS_FORM2_FORM2_CTRL_ID,
    MMI_DUERAPP_ASSISTS_FORM2_FORM1_IMAGE_CTRL_ID,//喇叭图片
    MMI_DUERAPP_ASSISTS_FORM2_FORM1_LABEL_CTRL_ID,//喊爸妈来扫码
    MMI_DUERAPP_ASSISTS_FORM2_FORM2_LABEL_CTRL_ID,//使用微信扫码开会员
    MMI_DUERAPP_ASSISTS_FORM2_FORM2_OWNER_DRAW_CTRL_ID,//自绘制

    //会员界面发送留言
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_CTRL_ID,//发给
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM2_CTRL_ID,//留言
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM3_CTRL_ID,//长图
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM1_CTRL_ID,//发给的绑定号码数量，当前最大10个
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM3_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM4_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM5_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM6_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM7_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM8_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM9_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM10_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM1_FORM1_CTRL_ID,//发给，当前最大10个
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM1_FORM2_CTRL_ID,//图片和XXX的微信，当前最大10个
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM2_FORM1_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM2_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM3_FORM1_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM3_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM4_FORM1_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM4_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM5_FORM1_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM5_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM6_FORM1_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM6_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM7_FORM1_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM7_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM8_FORM1_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM8_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM9_FORM1_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM9_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM10_FORM1_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM10_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM1_FORM1_LABEL_CTRL_ID,//发给，当前最大10个
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM1_FORM2_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM1_FORM2_LABEL_CTRL_ID,//XXX的微信，当前最大10个
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM2_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM2_FORM2_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM2_FORM2_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM3_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM3_FORM2_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM3_FORM2_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM4_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM4_FORM2_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM4_FORM2_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM5_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM5_FORM2_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM5_FORM2_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM6_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM6_FORM2_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM6_FORM2_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM7_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM7_FORM2_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM7_FORM2_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM8_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM8_FORM2_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM8_FORM2_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM9_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM9_FORM2_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM9_FORM2_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM10_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM10_FORM2_CHECKBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM1_FORM10_FORM2_LABEL_CTRL_ID,
    
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM2_FORM1_CTRL_ID,//助力留言和编辑按钮
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM2_FORM2_CTRL_ID,//留言显示框
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM2_FORM3_CTRL_ID,//一键发送按钮
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM2_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM2_FORM1_BUTTON_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM2_FORM2_TEXTBOX_CTRL_ID,
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM2_FORM3_BUTTON_CTRL_ID,
    
    MMI_DUERAPP_VIP_TRANSMIT_MESSAGE_FORM3_ANIM_CTRL_ID,//长图的动画
    
    //会员界面助力留言
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM1_CTRL_ID,//助力留言
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_CTRL_ID,//更多模板
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM1_FORM1_CTRL_ID,//标题加编辑框，顺序排
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM1_FORM2_CTRL_ID,//语音输入和确认按钮，并列排
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM1_CTRL_ID,//标题
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_CTRL_ID,//文字列表
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_FORM1_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_FORM2_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_FORM3_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_FORM4_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_FORM5_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_FORM6_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_FORM7_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_FORM8_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM1_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM1_FORM1_EDIT_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM1_FORM2_BUTTON1_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM1_FORM2_BUTTON2_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM1_LABEL_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_BUTTON1_CTRL_ID,//固定8个按钮模板及TEXTBOX选项
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_BUTTON2_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_BUTTON3_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_BUTTON4_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_BUTTON5_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_BUTTON6_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_BUTTON7_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_BUTTON8_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_TEXTBOX1_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_TEXTBOX2_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_TEXTBOX3_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_TEXTBOX4_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_TEXTBOX5_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_TEXTBOX6_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_TEXTBOX7_CTRL_ID,
    MMI_DUERAPP_VIP_MESSAGE_SELECT_FORM2_FORM2_TEXTBOX8_CTRL_ID,

    #include "duerapp_homepage_id.h"
    // #include "duerinput_id.h"


    DUERAPP_MAX_CTRL_ID
} DUERAPP_CONTROL_ID_E;

/**--------------------------------------------------------------------------*
 **                         FUNCTION DEFINITION                              *
 **--------------------------------------------------------------------------*/

PUBLIC void MMIDUERAPP_RegWinIdNameArr(void);

/**--------------------------------------------------------------------------*
 **                         Compiler Flag                                    *
 **--------------------------------------------------------------------------*/
#ifdef   __cplusplus
    }
#endif

#endif //_MMIHELLO_ID_H_
