
//[[define image information

//]]define image information



//[[define anim information

//]]define anim information


//[[define string information

RES_ADD_STRING(HANZI_CARD,"汉字学习")
RES_ADD_STRING(HANZI_PACTISE,"汉字学习")
RES_ADD_STRING(HANZI_NEW_WORD,"生词本")
RES_ADD_STRING(HANZI_MASTERED,"已掌握")
RES_ADD_STRING(HANZI_UNMASTERED,"未掌握")
RES_ADD_STRING(HANZI_NEXT_CHAPTER,"下一单元")
RES_ADD_STRING(HANZI_BACK_CHAPTER,"返回")
RES_ADD_STRING(HANZI_RENJIAO_EDITION,"人教版")
RES_ADD_STRING(HANZI_SIMILAR_WORD,"【形近字】")
RES_ADD_STRING(HANZI_NO_UNMASTER,"本单元暂无未掌握的汉字")
RES_ADD_STRING(HANZI_CONTINUE_TIPS,"是否继续上次学习")
RES_ADD_STRING(HANZI_OPEN_AUTOPLAY,"已开启自动发音")
RES_ADD_STRING(HANZI_CLOSE_AUTOPLAY,"已关闭自动发音")
RES_ADD_STRING(HANZI_LOADING_WAIT,"正在加载，请稍后")
RES_ADD_STRING(HANZI_NONE_AUDIO,"暂无音频")
RES_ADD_STRING(HANZI_LOAD_FAIL_WAIT,"音频加载失败，请重试")
RES_ADD_STRING(HANZI_DELETING_WAIT,"正在删除，请稍等")
RES_ADD_STRING(HANZI_LEARN_LISTENING_TIPS_2,"点击上方图片查看汉字")

//]]define string information




//#endif