
//[[define image information

//RES_ADD_IMG(IMG_DIALPAD_0,"\\MMI_RES_##\\IMAG\\DIALPAD_0.png",IMG_CMP_PNG_ARGB_RLE,0)    
	RES_ADD_IMG(IMG_POETRY_FAVORITELIST,"\\MMI_RES_##\\IMAG\\poetry_favoritelist.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_ZMT_FAVORITE,"\\MMI_RES_##\\IMAG\\favorite.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_ZMT_NOTFAVORITE,"\\MMI_RES_##\\IMAG\\notfavorite.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_FILE,"\\MMI_RES_##\\IMAG\\poetry_file.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_AUDOPLAY,"\\MMI_RES_##\\IMAG\\autoplay.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_DISAUTOPLAY,"\\MMI_RES_##\\IMAG\\disautoplay.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_PLAY,"\\MMI_RES_##\\IMAG\\poetry_play.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_BG,"\\MMI_RES_##\\IMAG\\poetry_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_DETAIL_BG,"\\MMI_RES_##\\IMAG\\poetry_detailbg.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_ITEM_BG,"\\MMI_RES_##\\IMAG\\poetry_item_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image information



//[[define anim information


//]]define anim information


//[[define string information
    RES_ADD_STRING(ZMT_TXT_POETRY, "古诗词")
    RES_ADD_STRING(ZMT_TXT_POETRY_STUDY, "诗词学习")
    RES_ADD_STRING(ZMT_TXT_POETRY_AUTO, "自动")
    RES_ADD_STRING(ZMT_TXT_POETRY_FAVORITE, "收藏夹")
    RES_ADD_STRING(ZMT_TXT_POETRY_NO_INFO, "暂无古诗词")
    RES_ADD_STRING(ZMT_TXT_POETRY_NO_FAVORITE, "暂无收藏")
    RES_ADD_STRING(ZMT_TXT_POETRY_LOADING, "加载中")
    RES_ADD_STRING(ZMT_TXT_POETRY_LOAD_FAILED, "加载失败")
    RES_ADD_STRING(ZMT_TXT_POETRY_CONTENT_OPTIONS, "原文")
    RES_ADD_STRING(ZMT_TXT_POETRY_EXPRESSION_OPTIONS, "注释")
    RES_ADD_STRING(ZMT_TXT_POETRY_TRANSLATE_OPTIONS, "翻译")
    RES_ADD_STRING(ZMT_TXT_POETRY_APPRECIATION_OPTIONS, "赏析")
    RES_ADD_STRING(ZMT_TXT_POETRY_REFRESH, "刷新")
    RES_ADD_STRING(ZMT_TXT_POETRY_NO_COMMENT, "暂无注释")
    RES_ADD_STRING(ZMT_TXT_POETRY_NO_APPRECIATION, "暂无赏析")
    RES_ADD_STRING(ZMT_TXT_POETRY_OPEN_AUTOPLAY, "已开启自动朗读")
    RES_ADD_STRING(ZMT_TXT_POETRY_CLOSE_AUTOPLAY, "已关闭自动朗读")
    RES_ADD_STRING(ZMT_TXT_POETRY_PLAYING, "正在播放音频")
    RES_ADD_STRING(ZMT_TXT_POETRY_DOWNLOADING, "正在下载音频")
	
//]]define string information