
//[[define image information

//RES_ADD_IMG(IMG_DIALPAD_0,"\\MMI_RES_##\\IMAG\\DIALPAD_0.png",IMG_CMP_PNG_ARGB_RLE,0)    
	RES_ADD_IMG(IMG_POETRY_FAVORITELIST,"\\MMI_RES_##\\IMAG\\poetry_favoritelist.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_ZMT_FAVORITE,"\\MMI_RES_##\\IMAG\\favorite.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_ZMT_NOTFAVORITE,"\\MMI_RES_##\\IMAG\\notfavorite.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_FILE,"\\MMI_RES_##\\IMAG\\poetry_file.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_AUDOPLAY,"\\MMI_RES_##\\IMAG\\autoplay.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_DISAUTOPLAY,"\\MMI_RES_##\\IMAG\\disautoplay.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_PLAY,"\\MMI_RES_##\\IMAG\\poetry_play.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_BG,"\\MMI_RES_##\\IMAG\\poetry_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_DETAIL_BG,"\\MMI_RES_##\\IMAG\\poetry_detailbg.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_ITEM_BG,"\\MMI_RES_##\\IMAG\\poetry_item_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image information



//[[define anim information


//]]define anim information


//[[define string information
    RES_ADD_STRING(ZMT_TXT_POETRY, "¹ÅÊ«´Ê")
    RES_ADD_STRING(ZMT_TXT_POETRY_STUDY, "Ê«´ÊÑ§Ï°")
    RES_ADD_STRING(ZMT_TXT_POETRY_AUTO, "×Ô¶¯")
    RES_ADD_STRING(ZMT_TXT_POETRY_FAVORITE, "ÊÕ²Ø¼Ð")
    RES_ADD_STRING(ZMT_TXT_POETRY_NO_INFO, "ÔÝÎÞ¹ÅÊ«´Ê")
    RES_ADD_STRING(ZMT_TXT_POETRY_NO_FAVORITE, "ÔÝÎÞÊÕ²Ø")
    RES_ADD_STRING(ZMT_TXT_POETRY_LOADING, "¼ÓÔØÖÐ")
    RES_ADD_STRING(ZMT_TXT_POETRY_LOAD_FAILED, "¼ÓÔØÊ§°Ü")
    RES_ADD_STRING(ZMT_TXT_POETRY_CONTENT_OPTIONS, "Ô­ÎÄ")
    RES_ADD_STRING(ZMT_TXT_POETRY_EXPRESSION_OPTIONS, "×¢ÊÍ")
    RES_ADD_STRING(ZMT_TXT_POETRY_TRANSLATE_OPTIONS, "·­Òë")
    RES_ADD_STRING(ZMT_TXT_POETRY_APPRECIATION_OPTIONS, "ÉÍÎö")
    RES_ADD_STRING(ZMT_TXT_POETRY_REFRESH, "Ë¢ÐÂ")
    RES_ADD_STRING(ZMT_TXT_POETRY_NO_COMMENT, "ÔÝÎÞ×¢ÊÍ")
    RES_ADD_STRING(ZMT_TXT_POETRY_NO_APPRECIATION, "ÔÝÎÞÉÍÎö")
	
//]]define string information