
//[[define image information


RES_ADD_IMG(MATH_COUNT_ADD_IMG,"\\MMI_RES_##\\IMAG\\add.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MATH_COUNT_REDUCE_IMG,"\\MMI_RES_##\\IMAG\\reduce.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MATH_COUNT_CORRECT_IMG,"\\MMI_RES_##\\IMAG\\math_correct.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MATH_COUNT_WRONG_IMG,"\\MMI_RES_##\\IMAG\\math_wrong.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(MATH_COUNT_KEYBOARD_IMG,"\\MMI_RES_##\\IMAG\\math_keyboard.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_MATH_COUNT_RANK,"\\MMI_RES_##\\IMAG\\math_count_rank.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_MATH_COUNT_TASK,"\\MMI_RES_##\\IMAG\\math_count_task.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image information



//[[define anim information


//]]define anim information


//[[define string information

	RES_ADD_STRING(MATH_COUNT_TITLE, "口算达人")
    RES_ADD_STRING(MATH_COUNT_COUNTING_BACK, "返回")
    RES_ADD_STRING(MATH_COUNT_SCORE_BACK, "排行榜")
    RES_ADD_STRING(MATH_COUNT_SCORE_LOADING, "加载中")
    RES_ADD_STRING(MATH_COUNT_SCORE_UPDATING, "更新排行榜中")
    RES_ADD_STRING(MATH_COUNT_SCORE_LOAD_FAIL, "加载排行榜失败")
    RES_ADD_STRING(MATH_COUNT_SCORE_RE_LOAD, "刷新")
    RES_ADD_STRING(MATH_COUNT_SCORE_RANK_RANK, "排行")
    RES_ADD_STRING(MATH_COUNT_SCORE_RANK_NAME, "姓名")
    RES_ADD_STRING(MATH_COUNT_SCORE_RANK_SCORE, "总分")
    RES_ADD_STRING(MATH_COUNT_AGAIN, "再来一次")
    RES_ADD_STRING(MATH_COUNT_TODAY, "今日题数")
    RES_ADD_STRING(MATH_COUNT_RIGHT, "正确题数")
    RES_ADD_STRING(MATH_COUNT_RIGHT_PERCENT, "正确率")
    RES_ADD_STRING(MATH_COUNT_TASK_LOAD_FAIL, "加载学习成果失败")
    RES_ADD_STRING(MATH_COUNT_TASK_NONE, "暂无学习成果")
    RES_ADD_STRING(MATH_COUNT_RANK_NONE, "暂无排行榜")
    
	
//]]define string information