
//[[define image information

//RES_ADD_IMG(IMG_DIALPAD_0,"\\MMI_RES_##\\IMAG\\DIALPAD_0.png",IMG_CMP_PNG_ARGB_RLE,0)    
	RES_ADD_IMG(IMG_POETRY_FAVORITELIST,"\\MMI_RES_##\\IMAG\\poetry_favoritelist.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_DSL_FAVORITE,"\\MMI_RES_##\\IMAG\\favorite.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_DSL_NOTFAVORITE,"\\MMI_RES_##\\IMAG\\notfavorite.png",IMG_CMP_PNG_ARGB_RLE,0)
	RES_ADD_IMG(IMG_POETRY_FILE,"\\MMI_RES_##\\IMAG\\poetry_file.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image information



//[[define anim information


//]]define anim information


//[[define string information
    RES_ADD_STRING(READBOY_TXT_POETRY, "古诗词")
    RES_ADD_STRING(READBOY_TXT_POETRY_STUDY, "诗词学习")
    RES_ADD_STRING(READBOY_TXT_POETRY_FAVORITE, "收藏夹")
	RES_ADD_STRING(READBOY_TXT_POETRY_NO_INFO, "暂无古诗词")
    RES_ADD_STRING(READBOY_TXT_POETRY_NO_FAVORITE, "暂无收藏")
    RES_ADD_STRING(READBOY_TXT_POETRY_LOADING, "加载中")
    RES_ADD_STRING(READBOY_TXT_POETRY_LOAD_FAILED, "加载失败")
    RES_ADD_STRING(READBOY_TXT_POETRY_CONTENT_OPTIONS, "原文")
    RES_ADD_STRING(READBOY_TXT_POETRY_EXPRESSION_OPTIONS, "注释")
    RES_ADD_STRING(READBOY_TXT_POETRY_TRANSLATE_OPTIONS, "翻译")
    RES_ADD_STRING(READBOY_TXT_POETRY_APPRECIATION_OPTIONS, "赏析")
    RES_ADD_STRING(READBOY_TXT_POETRY_REFRESH, "刷新")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT, "权益中心")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_TIP_TITLE, "温馨提示")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_GO_DEPOSIT, "去充值")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_LATER_GO_DEPOSIT, "以后再说")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_CHOOSE_ORDER, "套餐 话费加油包 流量加油包")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_ORDER_REMAIN_A, "套餐有效期剩余:")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_ORDER_REMAIN_B, "本月通话剩余:")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_ORDER_REMAIN_C, "本月流量剩余:")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_PLEASE_USE_WECHAT, "请使用微信扫码支付")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_PLEASE_USE_ALIPAY, "请使用支付宝扫码支付")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_PLEASE_CHANGE_WECHAT, "切换为微信支付")
    RES_ADD_STRING(READBOY_TXT_DEPOSIT_PLEASE_CHANGE_ALIPAY, "切换为支付宝支付")
	
//]]define string information