
//[[define image information

RES_ADD_IMG(IMG_ZMT_GPT_KOUYU,"\\MMI_RES_##\\IMAG\\dream_gpt_kouyu.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_ZUOWEN,"\\MMI_RES_##\\IMAG\\dream_gpt_zuowen.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_TALK_ICON,"\\MMI_RES_##\\IMAG\\dream_gpt_talk.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_NET_ERROR,"\\MMI_RES_##\\IMAG\\dream_gpt_net_error.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_REQUEST_FAIL,"\\MMI_RES_##\\IMAG\\dream_gpt_request_fail.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_CANCEL,"\\MMI_RES_##\\IMAG\\dream_gpt_cancel.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_OK,"\\MMI_RES_##\\IMAG\\dream_gpt_ok.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_AI_VOICE,"\\MMI_RES_##\\IMAG\\dream_gpt_ai_voice.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_MINE_VOICE,"\\MMI_RES_##\\IMAG\\dream_gpt_mind_voice.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_LOOP_RECORD,"\\MMI_RES_##\\IMAG\\dream_gpt_loop.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_RECORD_1,"\\MMI_RES_##\\IMAG\\dream_gpt_record_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_RECORD_2,"\\MMI_RES_##\\IMAG\\dream_gpt_record_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_RECORD_3,"\\MMI_RES_##\\IMAG\\dream_gpt_record_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_RECORD_4,"\\MMI_RES_##\\IMAG\\dream_gpt_record_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_RECORD_5,"\\MMI_RES_##\\IMAG\\dream_gpt_record_5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_RECORD_6,"\\MMI_RES_##\\IMAG\\dream_gpt_record_6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_RECORD_7,"\\MMI_RES_##\\IMAG\\dream_gpt_record_7.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_RECORD_8,"\\MMI_RES_##\\IMAG\\dream_gpt_record_8.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_RECORD_9,"\\MMI_RES_##\\IMAG\\dream_gpt_record_9.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_LOAD_1,"\\MMI_RES_##\\IMAG\\dream_gpt_load_1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_LOAD_2,"\\MMI_RES_##\\IMAG\\dream_gpt_load_2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_LOAD_3,"\\MMI_RES_##\\IMAG\\dream_gpt_load_3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_LOAD_4,"\\MMI_RES_##\\IMAG\\dream_gpt_load_4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_LOAD_5,"\\MMI_RES_##\\IMAG\\dream_gpt_load_5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_LOAD_6,"\\MMI_RES_##\\IMAG\\dream_gpt_load_6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_LOAD_7,"\\MMI_RES_##\\IMAG\\dream_gpt_load_7.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_LOAD_8,"\\MMI_RES_##\\IMAG\\dream_gpt_load_8.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_ZMT_GPT_LOAD_9,"\\MMI_RES_##\\IMAG\\dream_gpt_load_9.png",IMG_CMP_PNG_ARGB_RLE,0)

//]]define image information


//[[define string information

RES_ADD_STRING(ZMT_CHAT_GPT,"对话GPT")
RES_ADD_STRING(ZMT_CHAT_GPT_KOUYU,"英语对话")
RES_ADD_STRING(ZMT_CHAT_GPT_ZUOWEN,"续写作文")
RES_ADD_STRING(ZMT_CHAT_GPT_TOPIC,"选择话题")
RES_ADD_STRING(ZMT_CHAT_GPT_SAY_TEXT,"输入一段30字以内的开头，我帮你续写一篇作文")
RES_ADD_STRING(ZMT_CHAT_GPT_RECORD_TIPS,"松开发送，上划取消")
RES_ADD_STRING(ZMT_CHAT_GPT_RECORD_FAIL,"语音识别失败，n请重试")
RES_ADD_STRING(ZMT_CHAT_GPT_RECORD_ACTION,"长按开始录音")
RES_ADD_STRING(ZMT_CHAT_GPT_RECORD_INDENTIFY_NOW,"语音识别中，请稍等")
RES_ADD_STRING(ZMT_CHAT_GPT_LOADING,"加载中..")
RES_ADD_STRING(ZMT_CHAT_GPT_LOADING_FAIL,"加载失败")
RES_ADD_STRING(ZMT_CHAT_GPT_REQUSET_FAIL,"请求失败")
RES_ADD_STRING(ZMT_CHAT_GPT_RECORD_IDENTIFY_FAIL,"识别失败，请重试")
RES_ADD_STRING(ZMT_CHAT_GPT_RECORD_REQUESET_ERROR,"请求失败，请重试")

//]]define string information

