
//[[define image information

RES_ADD_IMG(IMG_ZMT_DIAL_STORE,"\\MMI_RES_##\\IMAG\\watch_dial_store.png",IMG_CMP_PNG_ARGB_RLE,0)

//]]define image information


//[[define string information

RES_ADD_STRING(ZMT_DIAL_STORE,"表盘商城")
RES_ADD_STRING(ZMT_DIAL_WEEK_CH_SUNDAY,"周日")
RES_ADD_STRING(ZMT_DIAL_WEEK_CH_MONDAY,"周一")
RES_ADD_STRING(ZMT_DIAL_WEEK_CH_TUESDAY,"周二")
RES_ADD_STRING(ZMT_DIAL_WEEK_CH_WEDNESDAY,"周三")
RES_ADD_STRING(ZMT_DIAL_WEEK_CH_THURSDAY,"周四")
RES_ADD_STRING(ZMT_DIAL_WEEK_CH_FRIDAY,"周五")
RES_ADD_STRING(ZMT_DIAL_WEEK_CH_SATURDAY,"周六")
RES_ADD_STRING(ZMT_DIAL_WEEK_EN_SUNDAY,"Sun")
RES_ADD_STRING(ZMT_DIAL_WEEK_EN_MONDAY,"Mon")
RES_ADD_STRING(ZMT_DIAL_WEEK_EN_TUESDAY,"Tue")
RES_ADD_STRING(ZMT_DIAL_WEEK_EN_WEDNESDAY,"Wed")
RES_ADD_STRING(ZMT_DIAL_WEEK_EN_THURSDAY,"Thu")
RES_ADD_STRING(ZMT_DIAL_WEEK_EN_FRIDAY,"Fri")
RES_ADD_STRING(ZMT_DIAL_WEEK_EN_SATURDAY,"Sat")

RES_ADD_STRING(ZMT_DIAL_STORE_LIST_REQUEST,"表盘列表加载中\n请稍等")
RES_ADD_STRING(ZMT_DIAL_STORE_REQUEST_FAIL,"获取失败\n请重试")
RES_ADD_STRING(ZMT_DIAL_STORE_REQUEST_ERROR,"网络加载有误\n请重试")
RES_ADD_STRING(ZMT_DIAL_STORE_PREVIEW_REQUESET,"预览图加载中\n请稍等")
RES_ADD_STRING(ZMT_DIAL_PREVIEW_DOWNLOAD_DIAL,"付费下载")
RES_ADD_STRING(ZMT_DIAL_PREVIEW_ALREADY_DOWNLOAD,"已下载，去使用")
//]]define string information

