/*****************************************************************************
** File Name:      zmt_class_mdu_def.h                                               *
** Author:         fys                                               *
** Date:           2024/06/27                                                *
******************************************************************************/

//[[define image information
RES_ADD_IMG(IMG_CLASS_ENGLISH,"\\MMI_RES_##\\IMAG\\class_english.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_CHINESE,"\\MMI_RES_##\\IMAG\\class_chinese.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_ENGLISH_BOOK,"\\MMI_RES_##\\IMAG\\class_english_book.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_CHINESE_BOOK,"\\MMI_RES_##\\IMAG\\class_chinese_book.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_MAIN_ITEM_BG,"\\MMI_RES_##\\IMAG\\class_main_item_bg.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_GRADE_ICON,"\\MMI_RES_##\\IMAG\\class_grade_icon.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_RECORD,"\\MMI_RES_##\\IMAG\\class_preview_record.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_RECORD_0,"\\MMI_RES_##\\IMAG\\class_preview_record0.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_RECORD_1,"\\MMI_RES_##\\IMAG\\class_preview_record1.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_RECORD_2,"\\MMI_RES_##\\IMAG\\class_preview_record2.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_RECORD_3,"\\MMI_RES_##\\IMAG\\class_preview_record3.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_RECORD_4,"\\MMI_RES_##\\IMAG\\class_preview_record4.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_RECORD_5,"\\MMI_RES_##\\IMAG\\class_preview_record5.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_RECORD_6,"\\MMI_RES_##\\IMAG\\class_preview_record6.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_RECORD_7,"\\MMI_RES_##\\IMAG\\class_preview_record7.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_RECORD_8,"\\MMI_RES_##\\IMAG\\class_preview_record8.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_PAUSE,"\\MMI_RES_##\\IMAG\\class_pause.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_PLAY,"\\MMI_RES_##\\IMAG\\class_play.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_SINGLE_FALSE,"\\MMI_RES_##\\IMAG\\class_single_false.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_SINGLE_TRUE,"\\MMI_RES_##\\IMAG\\class_single_true.png",IMG_CMP_PNG_ARGB_RLE,0)
RES_ADD_IMG(IMG_CLASS_SETTING,"\\MMI_RES_##\\IMAG\\class_setting.png",IMG_CMP_PNG_ARGB_RLE,0)
//]]define image information



//[[define anim information

//]]define anim information


//[[define string information

RES_ADD_STRING(CLASS_SYNR_TXT,"课堂同步")
RES_ADD_STRING(CLASS_SYNR_CHINESE_TXT,"语文课堂")
RES_ADD_STRING(CLASS_SYNR_ENGLISH_TXT,"英语课堂")
RES_ADD_STRING(CLASS_SYNR_GRADE_CHINESE_TXT,"语文年级选择")
RES_ADD_STRING(CLASS_SYNR_GRADE_ENGLISH_TXT,"英语年级选择")
RES_ADD_STRING(CLASS_SYNR_GRADE_1_TXT,"一年级")
RES_ADD_STRING(CLASS_SYNR_GRADE_2_TXT,"二年级")
RES_ADD_STRING(CLASS_SYNR_GRADE_3_TXT,"三年级")
RES_ADD_STRING(CLASS_SYNR_GRADE_4_TXT,"四年级")
RES_ADD_STRING(CLASS_SYNR_GRADE_5_TXT,"五年级")
RES_ADD_STRING(CLASS_SYNR_GRADE_6_TXT,"六年级")
RES_ADD_STRING(CLASS_SYNR_GRADE_7_TXT,"七年级")
RES_ADD_STRING(CLASS_SYNR_GRADE_8_TXT,"八年级")
RES_ADD_STRING(CLASS_SYNR_GRADE_9_TXT,"九年级")
RES_ADD_STRING(CLASS_SYNR_BOOK_TXT,"书本选择")
RES_ADD_STRING(CLASS_SYNR_LOADING_TXT,"加载中..")
RES_ADD_STRING(CLASS_SYNR_LOAD_FAIL_TXT,"加载失败")
RES_ADD_STRING(CLASS_SYNR_REQUEST_TXT,"请求失败")

RES_ADD_STRING(CLASS_SYNR_BOOK_READ_TXT,"课文范读")
RES_ADD_STRING(CLASS_SYNR_AI_EVALUATE_TXT,"AI评测")
RES_ADD_STRING(CLASS_SYNR_BOOK_READ_SET_TXT,"课文范读设置")
RES_ADD_STRING(CLASS_SYNR_READ_REPEAT_TXT,"单句复读次数")
RES_ADD_STRING(CLASS_SYNR_READ_REPEAT_1_TXT,"1次")
RES_ADD_STRING(CLASS_SYNR_READ_REPEAT_2_TXT,"2次")
RES_ADD_STRING(CLASS_SYNR_READ_REPEAT_3_TXT,"3次")
RES_ADD_STRING(CLASS_SYNR_READ_FONT_TXT,"课文字体大小")
RES_ADD_STRING(CLASS_SYNR_READ_FONT_1_TXT,"18")
RES_ADD_STRING(CLASS_SYNR_READ_FONT_2_TXT,"20")
RES_ADD_STRING(CLASS_SYNR_READ_FONT_3_TXT,"22")
RES_ADD_STRING(CLASS_SYNR_READ_SPEED_TXT,"播放倍速")
RES_ADD_STRING(CLASS_SYNR_READ_SPEED_1_TXT,"1.0倍")
RES_ADD_STRING(CLASS_SYNR_READ_SPEED_2_TXT,"2.0倍")
RES_ADD_STRING(CLASS_SYNR_READ_SPEED_3_TXT,"3.0倍")
//]]define string information

